export const CaseButtonStatusCode = {
	'ClearAllSelected': 3,
	'ScanAllSelected': 2,
	'CancelAllSelected': 4,
	'DeleteAllSelected': 6,
	'Clear': 3,
	'Scan': 2,
	'CancelCase': 4,
	'DecideLater': 1,
	'ReScanRequest': 16,
	'Emergency': 10,
	'Suspect': 14,
	'Inspect': 12,
	'AwaitingAssessment': 7,
	'AssessmentInProgress': 8,
	'AwaitingReAssessment': 9,
	'AwaitingInspection': 12,
	'InspectionInProgress': 13,
	'InspectionCleared': 15,
	'AssessmentCleared': 17,
	'ClearCase': 3,
	'ReScanCase':2,
	'ClearOnImage': 3,
	'SuspectOnImage': 14,
	'ScanCaseInDC': 2,
	'AwaitingInspectionCaseInDC': 12,
	'ClearCaseInDC': 3,
	'AwaitingScreeningInDC': 1,
	'InspectionRequested':11,
	'SuspectInDC': 14,
	'ReScanInDc': 2
};

export const caseEventCodes =
{
'CCE': 'Case Created',
'RDE': 'Ruler Deleted',
'RUFE': 'Ruler Update Failed',
'RUE' : 'Ruler Updated',
'RCFE' : 'Ruler Create Failed',
'RCE' : 'Ruler Created',
'FDFE' :'Finding Delete Failed',
'RDFE':'Ruler Delete Failed',
'FDE':'Finding Deleted',
'FUE':'Finding Updated',
'FCFE':'Finding Create Failed',
'FCE': 'Finding Created',
'CAIAE':'Case Assigned For Image Analysis',
'SAAFE':'Scan Auto Associate Failed',
'SAAE':'Scan Auto Associated',
'FUFE':'Finding Update Failed',
'VCE':'View Created',
'VCFE':'View Create Failed',
'VUE':'View Updated',
'CSCE':'Case State Changed',
'CVISFE':'Case Verdict Inspection Suspect Failed',
'CVISE':'Case Verdict Inspection Suspected',
'CVICFE':'Case Verdict Inspection Clear Failed',
'CVICE':'Case Verdict Inspection Cleared',
'CAIE':'Case Assigned For Inspection',
'CIRE':'Case Inspection Requested',
'CRRE':'Case Rescan Requested',
'CVASFE':'Case Verdict Assessment Suspect Failed',
'CVASE':'Case Verdict Assessment Suspected',
'CVACFE':'Case Verdict Assessment Clear Failed',
'CVACE':'Case Verdict Assessment Cleared',
'VDFE':'View Delete Failed',
'VDE':'View Deleted',
'VUFE':'View Update Failed',
'SMAFE':'Scan Manual Associate Failed',
'CSCFE':'Case State Change Failed',
'SMAE':'Scan Manually Associated',
'CPRFE':'Case Priority Remove Failed',
'CFDE':'Case File Deleted',
'CFAFE':'Case File Attach Failed',
'CFAE':'Case File Attached',
'CDDFE':'Case Draft Delete Failed',
'CDDE':'Case Draft Deleted',
'CDUFE':'Case Draft Update Failed',
'CFDFE':'Case File Delete Failed',
'CDUE':'Case Draft Updated',
'CDCE':'Case Draft Created',
'CDFE':'Case Delete Failed',
'CDE':'Case Deleted',
'CUFE':'Case Update Failed',
'CUE':'Case Updated',
'CCFE':'Case Create Failed',
'CDCFE':'Case Draft Create Failed',
'CRPRAE':'Case Risk Profiler Result Attached',
'CNRPRE':'Case No Risk Profiler Result',
'CVPCE':'Case Verdict Profiler Cleared',
'CPRE':'Case Priority Removed',
'CRAE':'Case Rescan Approved',
'CIAE':'Case Inpection Approved',
'CPFE':'Case Prioritize Failed',
'CPE':'Case Prioritized',
'CHFE':'Case Hold Failed',
'COHE':'Case OnHold',
'CRFE':'Case Release Failed',
'CRE':'Case Released',
'CPDOFE':'Case Profiler Decision OverrideFailed',
'CPDOE':'Case Profiler Decision Overridden',
'CRSE':'Case RAP Selected',
'CRPRUFE':'Case Risk Profiler Result Update Failed',
'CRPRUE':'Case Risk Profiler Result Updated',
'CVPCFE':'Case Verdict Profiler Clear Failed',
'SIAE':'Scan Images Added'

};
export const appLanguage = {
	1: 'en',
	10: 'fr',
	3: 'ge',
	8: 'de'
};
