export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
    'Login': 'Login_DE11',
    'UserId': 'User Id_DE',
    'EnterUserId': 'Please enter user id_DE',
    'EnterUserPassword': 'Please enter password_DE',
    'InvalidUserPassword': 'Invalid user name or password_DE',
    'Password': 'Password_DE',
    'RoleName': 'Role Name_DE',
    'Description': 'Description_DE',
    'Status': 'Status_DE1',
    'NewRoleDescription': 'Role Description_DE',
    'CreateNewRole': 'Create Role_DE',
    'GeneralInformation': 'General Information_DE',
    'RoleNameDuplicate': 'Role name already exists._DE',
    'RoleMandatoryFields': 'All mandatory fields must be provided to create a case_DE',
    'RolesNotExist': 'There are no roles created in the system_DE',
    'Required': 'This is a required field_DE',
    'OnlyNumber': 'Please enter numeric value_DE',
    'EnterRoleName': 'Please Enter Role Name_DE',
    'RoleExists': '%0 already exists, duplicate names not allowed please enter another name_DE',
    'EnterRoleDescription': 'Please Enter Role Description_DE',
    'RoleCloseMessage': 'You are leaving the window without saving it_DE',
    'SureCloseMessage': 'Are you sure you want to leave?_DE',
    'LeaveWithoutSaveButton': 'Leave without save_DE',
    'BackToWindowButton': 'Back to window_DE',
    'CasesNotExist': 'There are no Cases available in the system._DE',
    'TimeZone': 'Time Zone_DE',
    'Currency': 'Currency_DE',
    'Language': 'Language_DE',
    'DateFormat': 'Date Format_DE',
    'TimeFormat': 'Time Format_DE',
    'PFRM10000': 'Role is created successfully._DE',
    'PFRM10001': 'Duplicate role. Role name should be unique._DE',
    'PFRM10002': 'Please provide all the required information for creating a role_DE',
    'PFRM10003': 'Role Format Error. Role name should be alphanumeric with no special characters._DE',
    'PFRM10004': 'Role data is invalid._DE',
    'PFRM10100': 'Error occured while saving the role. Please try again later and contact admin if error persists._DE',
    'PFRM10999': 'Unknown exception occured while saving the role. Please contact admin if error persists._DE',
    'PFRM40100': 'Database Error occured while getting the roles. Please try again later and contact admin if error persists._DE',
    'PFRM30999': 'Unknown exception occured while updating the role. Please contact admin if error persists._DE',
    'PFRM40999': 'Unknown exception occured while getting the roles. Please contact admin if error persists._DE',
    'PFRM30100': 'Database error while saving the roles_DE',
    'PFRM40000': 'Roles Details fetched successfully_DE',
    'SACM10000': 'Case is submitted successfully._DE',
    'SACM10002': 'Please provide all the required information for creating a case._DE',
    'SACM10003': 'Case Format Error. Please make sure all the case properties are in right format._DE',
    'SACM10004': 'Invalid case management data._DE',
    'SACM10100': 'Error occured while saving the case. Please try again later and contact admin if error persists._DE',
    'SACM10999': 'Unknown exception occured while saving the case. Please contact admin if error persists._DE',
    'SACM40100': 'Database Error occured while getting the cases. Please try again later and contact admin if error persists._DE',
    'SACM40000': 'Case Details fetched successfully_DE',
    'SACM40999': 'Unknown exception occured while getting the case. Please contact admin if error persists_DE',
    'PFAM10000': 'Application was submitted successfully_DE',
    'PFAM10002': 'Please provide all the required information for creating an Application._DE',
    'PFAM10003': 'Application Format Error. Please make sure all the application properties are in right format._DE',
    'PFAM10004': 'Invalid application data._DE',
    'PFAM10100': 'Error occured while saving the application. Please try again later and contact admin if error persists._DE',
    'PFAM10999': 'Unknown exception occured while saving the application. Please contact admin if error persists._DE',
    'PFAM40100': 'Database Error occured while getting the applications. Please try again later and contact admin if error persists._DE',
    'PFAM40000': 'Applications Details fetched successfully_DE',
    'PFAM40999': 'Unknown exception occured while getting the apps details. Please contact admin if error persists._DE',
    'PFCC40100': 'Database Error occured while getting the customers data. Please try again later and contact admin if error persists._DE',
    'PFCC40000': 'Customers Details fetched successfully_DE',
    'PFCC40999': 'Unknown exception occured while getting the customers details. Please contact admin if error persists._DE',
    'PFUM10000': 'User created successfully._DE',
    'PFUM10001': 'Duplicate User. User details should be unique._DE',
    'PFUM10002': 'Please provide all the required information for creating a user_DE',
    'PFUM10003': 'User Format Error. User name should be alphanumeric with no special characters._DE',
    'PFUM10004': 'User data is invalid._DE',
    'PFUM10100': 'Error occured while saving the user. Please try again later and contact admin if error persists._DE',
    'PFUM10999': 'Unknown exception occured while saving the user. Please contact admin if error persists._DE',
    'PFUM40100': 'Database Error occured while getting the users. Please try again later and contact admin if error persists._DE',
    'PFUM40999': 'Unknown exception occured while getting the users. Please contact admin if error persists._DE',
    'PFUM40000': 'Users Details fetched successfully_DE',
    'PFUM30000': 'User updated successfully._DE',
    'PFUM30002': 'Please provide all the required information for updating a user_DE',
    'PFUM30003': 'User Format Error. User name should be alphanumeric with no special characters._DE',
    'PFUM30004': 'User data is invalid._DE',
    'PFUM30100': 'Error occured while saving the user. Please try again later and contact admin if error persists._DE',
    'PFUM30999': 'Unknown exception occured while saving the user. Please contact admin if error persists._DE',
    'PFUM40004': 'Error occured while getting the user details_DE',
    'PFSM40000': 'Successful Security _DE',
    'PFSM40002': 'Mandatory information missing_DE',
    'PFSM40004': 'Security data invalid_DE',
    'ContainerID': 'Container ID_DE',
    'Weight': 'Weight_DE1',
    'Length': 'Length_DE1',
    'From': 'From_DE111',
    'Country': 'Country_DE111',
	  'OriginPort':'Origin Port_DE',
	  'DestinationPort':'Destination Port_DE',
    'To': 'To_DE11111',
    'Company': 'Company_DE',
    'CreateCaseButton': 'Create Case_DE',
    'CreateCaseSuccess': 'A new case has been submitted_DE',
    'Alert': 'Alert_DE11',
    'Ok': 'OK_DE11111',
    'Reset': 'Reset_DE11',
    'EnterContainerId': 'Please enter container ID_DE',
    'EnterCompany': 'Please enter company_DE',
    'ContainerLength': 'Container length should not be more than 50_DE',
    'ContainerWeight': 'Container weight should not be more than 100_DE',
    'NotAuthorized': 'You are not authorized to perform this action._DE',
    'DefaultError': 'Error occured while performing the current operation. Please try again later and contact admin if error persists._DE',
    'RightsReserved': 'All rights reserved_DE',
    'Settings': 'Settings_DE',
    'AppsNotAssigned': 'You have not been assigned any applications. Please contact admin_DE',
    'NotAssignedApps': 'You have not assigned any Applications._DE',
    'Create': 'Create_DE1',
    'Cancel': 'Cancel_DE1',
    'CreateRoleQuestion': 'Do you want to create the role?_DE',
    'Yes': 'Yes_DE1111',
    'No': 'No_DE11111',
    'General': 'General_DE',
    'Users': 'Users_DE11',
    'Roles': 'Roles_DE11',
    'Applications': 'Applications_DE',
    'Apps': 'Applications_DE',
    'LocationSetting': 'Locations_DE',
    'LocalSettings': 'Local Settings_DE',
    'RegionalSettings': 'Regional Settings_DE',
    'MeasureUnit': 'Measure Unit_DE',
    'ChangesSave': 'Changes saved successfully_DE',
    'NotSavedChanges': 'Warning: You have not saved your changes._DE',
    'LeaveMessage': 'Are you sure you want to leave?_DE',
    'RoleInactiveMessage1': 'Warning: You have made the role inactive, there are users assigned to this role._DE',
    'RoleInactiveMessage2': 'The users will not be able to view this role once deactivated._DE',
    'RoleInactiveLeaveMessage': 'Are you sure you want to deactivate the role?_DE',
    'RoleCreated': 'Role created_DE',
    'FilterBy': 'Filter By_DE',
    'Save': 'Save_DE111',
    'OrgId': 'Org ID_DE1',
    'OrgIdLabel': 'Org ID_DE1',
    'fullName': 'Full Name_DE',
    'Id': 'ID_DE11111',
    'AccountCreate': 'Account Created_DE',
    'Email': 'Email_DE11',
    'Telephone': 'Telephone_DE',
    'EmpStatus': 'Employment Status_DE',
    'Position': 'Position_DE',
    'Mobile': 'Mobile_DE1',
    'AddNewUser': 'Add New User_DE',
    'AddNewRole': 'Add New Role_DE',
    'CreateUserProfile': 'Add New User_DE',
    'NoUserFound': 'No User Found_DE',
    'NoResultFound': 'No Result Found_DE',
    'NotAssignedRoles': 'You have not assigned any Roles._DE',
    'CreateUserQuestion': 'Do you want to create the user?_DE',
    'SaveMessageQuestion': 'Do you want to save the changes?_DE',
    'InvalidEmail': 'Email is invalid_DE',
    'InvalidTelephone': 'Telephone is invalid_DE',
    'InvalidMobile': 'Mobile number is invalid_DE',
    'GeneralSettings': 'General Settings_DE',
    'User': 'Users_DE11',
    'MappedRoles': 'Mapped Roles_DE',
    'AppAdded': 'App Added_DE',
    'AppPublished': 'App Published_DE',
    'AppLastUpdated': 'App Last Updated_DE',
    'AppVersion': 'Version_DE',
    'Type': 'Type_DE111',
    'Category': 'Category_DE',
    'Arrivals': 'Arrivals_DE',
    'MyCases': 'My Cases_DE',
    'CreateNewCase': 'Create New Case_DE',
    'CreateCase': 'Create a case_DE',
    'Search': 'Search_DE1',
    'ClearAllSelected': 'Clear All Selected_DE',
    'ScanAllSelected': 'Scan All Selected_DE',
    'CancelAllSelected': 'Cancel All Selected_DE',
    'CaseIdText': 'Case Id_DE',
    'CaseId': 'Case Id_DE',
    'CASEID': 'FR_CASEID_DE',
    'StartSearching': 'Start Searching_DE',
    'UpdatedDate': 'UpdatedDate_DE',
    'ControlCenterCaseId': 'Case Id_DE',
    'ContainerId': 'Container Id_DE',
    'Container': 'Container_DE',
    'HSCode': 'Harmonised System Code_DE',
    'HSCodes': 'Harmonised System Codes_DE',
    'HSCodesText': 'Harmonised System Codes_DE',
    'hscodeToolTip': 'Mutiple HSCodes should be seperated by a single comma_DE',
    'DateCreated': 'Date Created_DE',
    'LastModifiedDate': 'Last Modified Date_DE',
    'LastModified': 'Last Modified_DE',
    'ShippingCompany': 'Shipping Company_DE',
    'DateOfArrival': 'Date of Arrival_DE',
    'ArrivalDateSearch': 'Arrival Date_DE',
    'ShipId': 'Ship Id_DE',
    'ShipIdText' : 'Ship Id_DE',
    'InvalidEntry': 'Entry does not match validation criteria, please edit_DE',
    'InvalidShipEntry': 'Entry does not match validation criteria. Ship ID Should be IMO9176187 Format)._DE',
    'InvalidHsCodeEntry': 'Entry does not match validation criteria. HS Code Should be Numeric._DE',
    'InvalidWeightEntry': 'Entry does not match validation criteria. Weight should be in kgs (Up to two Decimals)._DE',
    'InvalidContainerIDEntry': 'Entry does not match validation criteria. Container ID should be Alpha-numeric._DE',
    'MyDrafts': 'My Drafts_DE',
    'AllCases': 'All Cases_DE',
    'VehicleInformation': 'Vehicle Information_DE',
    'PlateNumber': 'Plate Number_DE',
    'VehicleMake': 'Vehicle Make_DE',
    'DriverName': 'Driver Name_DE',
    'VehicleCompany': 'Vehicle Company_DE',
    'VehicleModal': 'Vehicle Model_DE',
    'DriverLicense': 'Driver License_DE',
    'ContainerInformation': 'Container Information_DE',
    'CaseLastUpdated': 'Last Updated On_DE',
    'CaseLastUpdatedBy': 'Last Updated By_DE',
    'ManualCaseCreation': 'Create a case_DE',
    'CaseDetails': 'Case Details_DE',
    'QueryBuilder': 'Query Builder_DE',
    'SearchCases': 'Search Cases_DE',
    'CaseStatus': 'Status_DE1',
    'CaseStatusText': 'Status_DE1:',
    'Clear': 'Clear_DE',
    'Scan': 'Scan_DE111',
    'cancelCase': 'Cancel This Case_DE',
    'decideLater': 'Decide Later_DE',
    'CargoType': 'Cargo Type:_DE',
    'ExpandAllCasePanels': 'Expand All_DE',
    'CollapseAllCasePanels': 'Collapse All_DE',
    'CaseInformation': 'Case Information_DE',
    'caseInfoActions': 'More Actions_DE',
    'sender': 'Sender_DE1',
    'SenderAddress': 'Sender Address_DE',
    'CaseFrom': 'Origin Country_DE',
    'CaseTo': 'Destination Country_DE',
    'ArrivalDate': 'Date of Arrival_DE',
    'ArrivalDateText': 'Date of Arrival_DE',
    'OverAllWeight': 'Overall Weight(kgs)_DE',
    'OverAllWeightText':'Overall Weight_DE',
    'Notes': 'Notes_DE11',
    'NotesText': 'Notes_DE:1',
    'ShipInfomation': 'Ship Information_DE',
    'ShipCompany': 'Shipping Company_DE',
    'Containers': 'Container ID_DE',
    'Contact': 'Contact_DE1',
    'Nationality': 'Nationality_DE',
    'Attachments': 'Attachments_DE',
    'AddAttachments': 'Add Attachments_DE',
    'Update': 'Update_DE1',
    'SaveAsDraft': 'Save As Draft_DE',
    'UpdateDraft': 'Update Draft_DE',
    'CaseDraftValidationMessage': 'Case cannot be saved as draft. Please make sure to fill in the following fields: Arrival Date, Container ID and Destination Country._DE',
    'Delete': 'Delete_DE1',
    'Close': 'Close_DE11',
    'DeleteAllSelected': 'Delete Selected_DE',
    'DeleteCaseQuestion': 'Are you sure you would like to delete the following case(s)?_DE',
    'ClearAllSelectedQuestion': 'Are you sure you would like to Clear the following case(s)?_DE',
    'CancelAllSelectedQuestion': 'Are you sure you would like to Cancel the following case(s)?_DE',
    'ScanAllSelectedQuestion': 'Are you sure you would like to Scan the following case(s)?_DE',
    'InspectAllSelectedQuestion': 'Are you sure you would like to Inspect the following case(s)?_DE',
    'SuspectAllSelectedQuestion': 'Are you sure you would like to Suspect the following case(s)?_DE',
    'ClearAllSelectedCasesText': 'We are going to clear following cases_DE',
    'SuspectAllSelectedCasesText': 'We are going to suspect following cases_DE',
    'InspectAllSelectedCasesText': 'Please select an Inspection Type for following cases_DE',
    'ScanAllSelectedCasesText': 'We are going to scan following cases_DE',
    'RescanAllSelectedCasesText': 'We are going to rescan the following Cases_DE',
    'FailedCaseListText': 'The following cases have failed_DE',
    'AwaitingScreeningSelectedCasesText': 'We are about to change the status of following cases to Awaiting Screening:_DE',
    'SaveChanges': 'Save Changes_DE',
    'ClearCaseQuestion': 'Are you sure you want to clear?_DE',
    'ScanCaseQuestion': 'Are you sure you want to send to scan?_DE',
    'SuspectCase': 'Are you sure you want to set the case as Suspect?_DE',
    'InspectCase': 'Are you sure you want to Inspect the Case?_DE',
    'ReScanRequest': 'Are you sure to request for Rescan of the case?_DE',
    'CancelCaseQuestion': 'Are you sure yu want to Cancel ?_DE',
    'UploadAttachment': 'Upload Attachment_DE',
    'AttachmentInfo': 'Please fill the following information for this attachment_DE',
    'Title': 'Title_DE11',
    'AttachmentDescription': ' is selected as an attachement of this case._DE',
    'Upload': 'Upload_DE1',
    'FieldsInfoMissing': '%0 field(s) information is missing_DE',
    'AddNewAttachment': 'Add New Attachment_DE',
    'Edit': 'Edit_DE111',
    'CharactersLeft': 'character(s) left_DE',
    'ConfirmAttachmentsDelete': 'Please confirm following attachments will be deleted_DE',
    'DeleteAttachments': 'Delete Attachments_DE',
    'Actions': 'Actions_DE',
    'ManageCases': 'Manage Cases_DE',
    'Suspect': 'Suspect_DE',
    'Activity': 'Activity_DE',
    'Refresh': 'Refresh_DE',
    'ViewCaseDetails': 'View Case Details_DE',
    'Screening': 'Screening_DE',
    'Override': 'Override_DE',
    'Inspect': 'Inspect_DE',
    'TrailerInformation': 'Trailer Information_DE',
    'AssessmentImages': 'Assessment Images_DE',
    'ImageAssessmentVerdict': 'Image Assessment Verdict_DE',
    'InspectionEvidence': 'Inspection Evidence_DE',
    'InspectionVerdict': 'Inspection Verdict_DE',
    'Displaying': 'Displaying_DE',
    'of': 'of_DE',
    'AwaitingScreening': 'Awaiting Screening_DE',
    'AwaitingScan': 'Awaiting Scan_DE',
    'Awaiting Screening': 'Awaiting Screening_DE',
    'Awaiting Scan': 'Awaiting Scan_DE',
    'Cleared': 'Cleared_DE',
    'Cancelled': 'Cancelled_DE',
    'Draft': 'Draft_DE11',
    'Deleted': 'Deleted_DE',
    'AwaitingAssessment': 'Awaiting Assessment_DE',
    'AssessmentInProgress': 'Assessment In Progress_DE',
    'AwaitingReAssessment': 'Re-Assessment Requested_DE',
    'Awaiting Assessment': 'Awaiting Assessment_DE',
    'Assessment InProgress': 'Assessment In Progress_DE',
    'Awaiting Re-Assessment': 'Awaiting Re-Assessment_DE',
    'Emergency': 'Emergency_DE',
    'InspectionRequested': 'Inspection Requested_DE',
    'AwaitingInspection': 'Awaiting Inspection_DE',
    'InspectionInProgress': 'Inspection In Progress_DE',
    'InspectionCleared': 'Inspection Cleared_DE',
    'ReScanRequested': 'Rescan Requested_DE',
    'AssessmentCleared': 'Assessment Cleared_DE',
    'Inspection Requested': 'Inspection Requested_DE',
    'Awaiting Inspection': 'Awaiting Inspection_DE',
    'Inspection in Progress': 'Inspection In Progress_DE',
    'Inspection Cleared': 'Inspection Cleared_DE',
    'Re-Scan Requested': 'Rescan Requested_DE',
    'Assessment Cleared': 'Assessment Cleared_DE',
    'Priority': 'Priority_DE',
    'Hold': 'Hold_DE',
    'EmptyMessage': 'There are no Cases that match your query_DE',
    'ClearCase': 'Clear Case_DE',
    'SuspectCaseId': 'Suspect Case _DE',
    'ReScanCaseId': 'The following case will be Rescanned_DE',
    'Loading': 'Loading...._DE',
    'ImageLoading': 'Image Loading...._DE',
    'ApplicationLoading': 'Application Loading..._DE',
    'RequestCaseReInspection': 'Request Inspection of Case_DE',
    'RequestCaseReAssess': 'Request Case Re-Assessment_DE',
    'EmptyReport': 'There are no finding associated to the report_DE',
    'ImageValidaitonMessage': 'No cases to be assessed_DE',
    'AssessmentSummary': 'Assessment Summary*_DE',
    'LoadNextCase': 'Load Next Case_DE',
    'MoreActions': 'MORE ACTIONS_DE',
    'RequestReAssessment': 'Request Reassessment_DE',
    'FitToWindow': 'Fit To Window_DE',
    'ImageSaveMessage': 'Would you like to save these changes as a new view?_DE',
    'NoResults': 'No Results Found_DE',
    'NoResultsMessage': 'Try widening your search_DE',
    'HSCodeGoodsType': 'HS Code/Goods Type_DE',
    'LeftorRight': 'Left Or Right_DE',
    'ToporBottom': 'Top Or Bottom_DE',
    'FrontorBack': 'Front or Back_DE',
    'Left': 'Left_DE111',
    'Right': 'Right_DE11',
    'Top': 'Top_DE1111',
    'Bottom': 'Bottom_DE1',
    'Front': 'Front_DE11',
    'Back': 'Back_DE111',
    'ImageAnalyzer': 'Image Analyser_DE',
    'Brightness': 'Brightness_DE',
    'Contrast': 'Contrast_DE',
    'DeleteFinding': 'Are you sure you want to delete the finding?_DE',
    'DeleteFindingHeader': 'Delete Finding_DE',
    'NoFindings': 'There are no findings associated with this Case._DE',
    'Finding_Category': 'Category_DE',
    'Finding_GoodsType': 'Goods Type/ HS Code_DE',
    'Finding_Description': 'Description_DE',
    'RequestReAssessmentVerdict': 'Request Reassessment_DE',
    'RequestReScanVerdict': 'Request Rescan_DE',
    'SuspectVerdict': 'Suspect_DE',
    'InspectVerdict': 'Inspect_DE',
    'ClearVerdict': 'Clear_DE',
    'ActionsVerdict': 'Actions_DE',
    'Finding_Declare': 'Declare_DE',
    'Finding_Declared': 'Declared_DE',
    'Finding_Confirm': 'Confirm_DE',
    'Finding_Confirmed': 'Confirmed_DE',
    'RulerDeleteQuestion': 'Are you sure you want to delete the Ruler?_DE',
    'RulerMark': 'Delete Ruler_DE',
    'AddRuler': 'Add Ruler_DE',
    'RulerCreationErrorMessage': 'Ruler Mark not long enough to be saved_DE',
    'ColorPreset': 'Color Presets_DE',
    'CaseLoading': 'Case Loading..._DE',
    'RiskRating': 'Risk Rating_DE',
    'LastUpdatedDate': 'Last Modified_DE',
    'LastUpdated': 'Last Modified Date_DE',
    'clearedCaseNote1': 'Cases available for_DE',
    'clearedCaseNote2': ' hours from cleared date_DE',
    'GridClearCaseLoading': 'Loading Clear Case details_DE',
    'PhysicalInspection': 'Physical Inspection_DE',
    'ClearCases': 'Clear Cases_DE',
    'Confirm': 'Confirm_DE',
    'Comments': 'Comments_DE',
    'PhysicalVerdict': 'Physical_DE',
    'SelectInspectionType': '- Please select an Inspection Type_DE',
    'SendToScreen': 'Send to Screen_DE',
    'AwaitingInspectionCases': 'Awaiting Inspection Cases_DE',
    'CreateNewView': 'Create New View_DE',
    'NoOfFindings': 'No of Findings_DE',
    'NoOfFindingsTooltip': 'No of Findings for the Case_DE',
    'ProfilerSettings': 'Profiler Settings_DE',
    'ReScanRequestText': 'Rescan Request_DE',
    'BackToList': 'Back To List_DE',
    'FindingsAndVerdict': 'Verdict_DE',
    'DCSettings': 'Decision Center Settings_DE',
    'ThresholdNumberRangeMessage': 'Please enter a number between 0 and 100_DE',
    'ThresholdNumberRangeMessageDC': 'Please enter a number between 0 and 10000_DE',
    'ThresholdTitleMessage': 'Changing the below thresholds will impact the overall Case Risk Score. All changes to these fields are recorded and audited. Please be aware that raising the threshold value results in higher risk items being passed through, and lowering the threshold value results in lower risk items being assessed._DE',
    'Threshold': 'Threshold_DE',
    'RiskCategory': 'Risk Category_DE',
    'FindingsCategory': 'Findings Category_DE',
    'InspectionType': 'Inspection Type_DE',
    'DiscardAndLeave': 'Discard And Leave_DE',
    'StayInApp': 'Stay in app_DE',
    'DiscardMessage': 'Would you like to leave the app and discard the changes?_DE',
    'AddNewFinding': 'Add New Finding_DE',
    'EvidenceAttached': 'Evidence Attached_DE',
    'ConfirmNewFinding': 'The following Finding will be created, please confirm._DE',
    'RiskLevel': 'Risk Level_DE',
    'RuleCategory': 'Category_DE',
    'CategoryScore': 'Score_DE',
    'ThresholdBreach': 'Breach_DE',
    'CaseRiskScore': 'Case Risk Score_DE',
    'CategoryScores': 'Category Scores_DE',
    'CreateFinding': 'Create a new Finding_DE',
    'CreateRuler': 'Create a new Ruler Mark_DE',
    'CaseTimeline': 'Case Timeline_DE',
    'batchId': 'Batch Id_DE',
    'containerIds': 'Container Id_DE',
    'scanTime': 'Scan Time_DE',
    'NoFilteredCases': 'There are no Cases available for inspection._DE',
    'NoFilteredInspectionCases': 'There is no case of ' + 'xxxx' + ' Inspection Type. Please clear filter or select another Inspection type._DE',
    'NoFilteredFindingCases': 'There is no case of ' + 'xxxx' + ' Findings Category. Please clear filter or select another Findings Category._DE',
    'RAPPathway': 'RAP Pathway_DE',
    'RapColour': 'RAP Colour_DE',
    'RapColourStatus': 'Initial Case status_DE',
    'MinRapScore': 'Minimum RAP Score_DE',
    'MaxRapScore': 'Maximum RAP Score_DE',
    'rapValidMessage': 'Please enter valid range number_DE',
    'ScanId': 'Scan Id_DE',
    'ScanDateTime': 'Date & Time Scan Created_DE',
    'SelectScanner': 'Select Scanner_DE',
    'FilterTable': 'Filter Table_DE',
    'ApplyFilter': 'Apply Filter_DE',
    'LoadScanner': 'Load Scanner_DE',
    'ChangeScanner': 'Change Scanner_DE',
    'ScanDate': 'Scan Date_DE',
    'AssociationStatus': 'Association Status_DE',
    'RiskScore': 'Risk Score_DE',
    'DCSetting': 'DC Settings_DE',
    'RapErrorMessage': 'Invalid value entered in Min/Max RAP Score field_DE',
    'English': 'English_DE',
    'French': 'French_DE',
    'German': 'German_DE',
    'English_DE': 'English',
    'French_DE': 'French',
    'German_DE': 'German',
    'AwaitingProfiling': 'Awaiting Profiling_DE',
    'CurrentStatus': 'Current Status_DE',
    'Ship': 'Ship:_DE',
    'DeparturePort': 'Departure Port_DE',
    'DepartureDate': 'Departure Date_DE',
    'MatchCaseHeaderText': 'Display Matching Case_DE',
    'MatchCaseInfoText': 'The following case matches the case information submitted. Can you either confirm that these are the same cases or that they are different cases_DE',
    'SerialNumber': 'Serial Number_DE',
    'Manufacturer': 'Manufacturer_DE',
    'ModelName': 'Model Name_DE',
    'UserName': 'User Name_DE',
    'Latitude': 'Location.Latitude_DE',
    'Longitude': 'Location.Longitude_DE',
    'DeviceID': 'Device Id_DE',
    'Display': 'Display_DE',
    'Location': 'Location_DE',
    'AssignedLicense': 'License_DE',
    'NoLicense': 'No Device License Available_DE',
    'NoUserLicense': 'No User License Available_DE',
    'DeviceSetting': 'Device Settings_DE',
    'AssessmentSummaryText': 'Assessment Summary_DE',
    'VerdictStatus': 'Verdict Status_DE',
    'operationalDashboard': 'Operational Dashboard_DE',
    'AssignLicense': 'License_DE',
    'Active': 'Active_DE1',
    'Inactive': 'Inactive_DE',
    'None': 'None_DE111',
    'Disabled': 'Disabled_DE',
    'ToggleLicenseFailure': 'Failure to Apply License_DE',
    'TargetImageAccessed': 'Target Images Assessed (per User per Hour)_DE',
    'FindingNumber': 'Finding Number_DE',
    'caseDetailId': 'Id_DE11111',
    'FindingAttachments': 'Finding Attachments_DE',
    'FileName': 'File Name_DE',
    'FileData': 'File Data_DE',
    'FileDescription': 'File Description_DE',
    'SelectedLocation': 'Location_DE',
    //dashboard translate constant
    'KPIS': 'KPIS_DE',
    'ScreenedAssessed': 'Screened & Assessed_DE',
    'Screened': 'Screened_DE',
    'Inspected': 'Inspected_DE',
    'Suspected': 'Suspected_DE',
    'TotalAssessments': 'Total Assessments_DE',
    'Target': 'TARGET_DE',
    'Actual': 'ACTUAL_DE',
    'Name': 'Name_DE111',
    'ShowHide': 'Show/Hide_DE',
    'Green': 'Green_DE',
    'Amber': 'Amber_DE',
    'Red': 'Red_DE',
    'Blue':'Blue_DE',
    'ImageAssesmentTitle': 'Image Assessment Compared to Target_DE',
    'Today': 'Today_DE',
    'Last24': 'Last 24 HRS_DE',
    'ActualLegend': 'Actual_DE',
    'TargetLegend': 'Target_DE',
    'ProfilerchartHeader': 'Profiler Resource Forecast Chart_DE',
    'TotalChart': 'Total Chart_DE',
    'TotalExpected': 'Total Expected_DE',
    'TotalProfiled': 'Total Profiled_DE',
    'RapColorChart': 'RAP Colour Chart_DE',
    'ProfiledCases': 'Profiled Cases_DE',
    'ExpectedCase': 'Expected Case_DE',
    'TotalProfiledCases':'Total Profiled Cases_DE',
    'TotalExpectedCases' : 'Total Expected Cases_DE',
    'SecureRedirection': 'Redirecting to Secure Login Page..._DE',
    'UnauthorisedAccess': 'Unauthorised Access_DE',
    'AdminContactMessage': 'You are not a registered user or your account does not have a valid licence. Please contact the system administrator._DE',
    'Attached':'Attached_DE',
    'UserTimeline':'User_DE',
    'NoRecordsFound':'No records found_DE',
    'NoAttachmentsFound':'No attachments found_DE',
    'ScanToColourMapping' :'Convert Scan to Colour Mapping_DE',
    'ScanToOriginalGreyscale': 'Convert Scan to original Greyscale_DE',
    'Organic': 'Organic_DE',
    'NonOrganic': 'Non-Organic_DE',
    'Metal': 'Metal_DE',
    'ShowFindings' :'Show Findings for this scan_DE',
    'HideFindings' :'Hide Findings for this scan_DE',
    'ShowRulers' :'Show Rulers for this scan_DE',
    'HideRulers' :'Hide Rulers for this scan_DE',
    'Effects':'Effects_DE',
    'Vizual':'ViZual_DE',
    'FitToView': 'Fit view_DE',
    'UserLoading': 'Loading Users..._DE',
    'UserDetailLoading': 'Loading User Details_DE',
    'SettingsLoading': 'Loading Settings..._DE',
    'SaveSettingsLoading': 'Save Settings_DE',
    'GeneralSettingsHeader': 'General Settings_DE',
    'UsersUpdating': 'Updating User..._DE',
    'UsersSaving': 'Saving User..._DE',
    'RolesUpdating': 'Updating Role..._DE',
    'RolesSaving': 'Saving Role..._DE',
    'RoleDetailLoading': 'Loading Role Details..._DE',
    'RoleLoading': 'Loading Roles..._DE',
    'SessionTimeout':'Session has expired_DE',
    'SessionExpireMessage':'You have been logged out due to inactivity._DE',
    'SessionRoute':'Click here to login_DE',
    'Note':'Note_DE',
    'ApplDetailLoading': 'Loading Application Details..._DE',
    'AppInformation': 'Applications Information_DE',
    'AppsUpdating': 'Updating Application..._DE',
    'ProfilerInfo' : 'Profiler Information_DE',
    'ProfilerSettingsLoading': 'Loading Profiler Settings..._DE',
    'ProfilerSettingsSaving': 'Saving Profiler Settings..._DE',
    'RAPPathwayInfo': 'RAP Pathway Information_DE',
    'RAPPathwayLoading': 'Loading RAP Pathway Settings..._DE',
    'RAPPathwaySaving' :'Saving RAP Pathway Settings..._DE',
    'Parameter': 'Parameter_DE',
    'Value': 'Value_DE',
    'DeviceLicenseInfo' : 'Device License Information_DE',
    'DeviceDetailLoading': 'Loading Device Details..._DE',
    'DeviceDetailSaving' :'Updating Device Details..._DE',
    'DecisionCentre':'Decision Centre_DE',
    'DecisionCenterInfo' : 'Decision Center Settings_DE',
    'DecisionCenterLoading': 'Loading Decision Center Settings..._DE',
    'DecisionCenterSaving' :'Saving Decision Center Settings..._DE',
    'LocationID' : 'Location Id_DE',
    'LocationName' : 'Location Name_DE',
    'LocationCode' : 'Location Code_DE',
    'OperationalDashBoardSetting' : 'Operational Dashboard Settings_DE',
    'DashboardLoading': 'Loading Operational Dashboard Settings..._DE',
    'DashboardSaving' :'Saving Operational Dashboard Settings..._DE',
    'Detail' : 'Detail_DE1',
    'Timeline' : 'Timeline_DE',
    'SavedViews' : 'Saved Views_DE',
    'Verdict' : 'Verdict_DE',
    'LogOut': 'Log out_DE',
    'CategoryType': 'Category Type_DE',
    'NIIStatus' : 'For NII -Status_DE',
    'RAPSelectedStatus' : 'For (RAD/NUC, De-Stuff, Canine) - Status_DE',
    'Source' : 'Source_DE',
    'ImageAssessment' : 'Image Assessment_DE',
    'Findings' : 'Findings_DE',
    'Finding': 'Finding_DE',
    'Action': 'Action_DE',
    'ApprovalRequest' : 'Approval Request_DE',
    'ApprovalRequestType' : 'Approval Request Type_DE',
    'HsCodeOrGoodsType' : 'HSCode / Goods Type_DE',
    'CaseCreation' : 'Case Creation_DE',
    'Profiler' : 'Profiler_DE',
    'View': 'View_DE111',
    'Ruler' : 'Ruler_DE11',
    'InspectorAssigned' : 'Inspector Assigned_DE',
    'InspectorVerdict' : 'Inspector Verdict_DE',
    'CasePriority' : 'Case Priority_DE',
    'CaseHold' : 'Case Hold_DE',
    'RiskColor' : 'Risk Color_DE',
    'Date' : 'Date_DE111',
    'Manual' : 'Manual_DE',
    'Attachment': 'Attachment_DE',
    'UserLabel' : 'User_DE111',
    'Evidence' : 'Evidence_DE',
    'AssignToSelf' : 'Assign To Self_DE',
    'Approval' : 'Approval_DE',
    'EnterContainerIDLabel' : 'Enter Container ID_DE',
    'EnterContainerIDNumber' : 'Enter Container ID Number_DE',
    'CorsysScanId' : 'CORSYS Scan Id_DE',
    'FindCase' : 'Find Case_DE',
    'PairCase' : 'Pair Case_DE',
    'Pair':'Pair_DE',
    'NoCaseFound' : 'No case found with this Container ID_DE',
    'CheckCase' : 'Please double check the number is correct or create a new case._DE',
    'ZoomIn' : 'zoom+_DE11',
    'ZoomOut' : 'zoom-_DE11',
    'DisplayOn' : 'Display On_DE',
    'DisplayOff' : 'Display Off_DE',
    'AddMark' : 'Add Mark_DE',
    'SaveComment' : 'Save Comment_DE',
    'SelectFromList' : 'Select from list_DE',
    'CancelCase' : 'Cancel the Case_DE',
    'Submit': 'Submit_DE1',
    'Leave' : 'Leave_DE11',
    'Assessment' : 'Assessment_DE',
    'RulerId' : 'Ruler Id_DE',
    'Shapes' : 'Shapes_DE',
    'AssessmentDetails' : 'Assessment Details_DE',
    'Comment': 'Comments_DE',
    'ScanAssociationFailed' : 'The Scan has failed to associate with the case, please try again_DE',
    'Success' : 'Success_DE',
    'StatusUpdated' : 'Status Updated_DE',
    'InspectCaseText' : 'Inspect Case_DE',
    'SuspectCaseText' : 'Suspect Case_DE',
    'VerdictClearCase' : 'Verdict - Clear Case_DE',
    'VerdictInspectCase' : 'Verdict - Inspect Case_DE',
    'VerdictSuspectCase' : 'Verdict - Suspect Case_DE',
    'UploadEvidence' : 'Upload Evidence_DE',
    'VerdictCase' : 'Verdict: Case:_DE',
    'SaveFinding' : 'Save Finding_DE',
    'LocationTitle':'Select a location_DE',
    'Destuff':'De-stuff_DE',
    'Canine':'Canine_DE',
    'RADNUC':'RAD/NUC_DE',
    'Heroin':'Heroin_DE',
    'Cocaine':'Cocaine_DE',
    'Marijuana':'Marijuana_DE',
    'Guns':'Guns_DE',
    'weapons':'Weapons_DE',
    'drugs':'Drugs_DE',
    'undeclared':'Undeclared_DE',
    'SupervisorCaseCleared':'Supervisor - Case Cleared_DE',
    'RapSelected':'Rap Selected_DE',
    'ScanAssociated':'Scan – Scan Associated_DE',
    'AnalyserReAssessment':'Analyser - Re-assessment_DE',
    'AnalyserfindingCreated':'Analyser Findings - Created_DE',
    'AnalyserfindingUpdated':'Analyser Findings - Updated_DE',
    'AnalyserfindingDeleted':'Analyser Findings - Deleted_DE',
    'AnalyserRulersDeleted':'Analyser Rulers - Deleted_DE',
    'AnalyserRulersUpdated':'Analyser Rulers - Updated_DE',
    'AnalyserRulersCreated':'Analyser Rulers - Created_DE',
    'AnalyserViewsCreated':'Analyser Views - Created_DE',
    'AnalyserViewsUpdated':'Analyser Views - Updated_DE',
    'AnalyserVerdictCleared':'Analyser Verdict - Cleared_DE',
    'AnalyserVerdictSuspect':'Analyser Verdict - Suspect_DE',
    'AnalyserVerdictInspect':'Analyser Verdict - Inspect_DE',
    'SupervisorRescanRequestApproval':'Supervisor - Rescan Re-Request Approval_DE',
    'SupervisorFlagHoldOnHold':'Supervisor - Flag – Hold – On Hold_DE',
    'SupervisorFlagHoldRemoved':'Supervisor - Flag – Hold – Removed_DE',
    'SupervisorFlagPriorityCase':'Supervisor - Flag – Priority – Case Prioritized_DE',
    'SupervisorFlagPriorityRemoved':'Supervisor - Flag – Priority – Removed_DE',
    'InspectionInspectorAssignedCase':'Inspection - Inspector Assigned_DE',
    'InspectionVerdictCleared':'Inspection - Verdict – Cleared_DE',
    'InspectionVerdictSuspect':'Inspection - Verdict – Suspect_DE',
    'InspectionVerdictAddNewFinding':'Inspection - Verdict – Add New Finding_DE',
    'InspectionVerdictEvidence':'Inspection - Verdict – Evidence_DE',
    'InspectionFindingsDeleted':'Inspection – Findings – Deleted_DE',
    'InspectionFindingsUpdated':'Inspection – Findings – Updated_DE',
    'InspectionFindingsCreated':'Inspection – Findings – Created_DE',
    'InspectionRulersUpdated':'Inspection – Rulers – Updated_DE',
    'InspectionRulersDeleted':'Inspection – Rulers – Deleted_DE',
    'ManualCaseCreatedFileAttachment':'Manual Case Created – File Attachment_DE',
    'ProfilerResult':'Profiler Result_DE',
    'ManualCaseCreated':'Manual Case Created_DE',
    'SupervisorDeStuffInspect':'Supervisor -De-Stuff- Inspect_DE',
    'SupervisorRADInspect':'Supervisor -RAD/NUC- Inspect_DE',
    'SupervisorCanineInspect':'Supervisor -Canine- Inspect_DE',
    'SupervisorNIIScan':'Supervisor - NII - Scan_DE',
    'AnalyserInspect':'Analyser - Inspect_DE',
    'AnalyserReScan':'Analyser Rescan_DE',
    'InspectionRulersCreated':'Inspection – Rulers – Created_DE',
    'SupervisorInspectionApproved':'Supervisor - Inspection Approved – Inspect_DE',
    'SupervisorDecisionOverride':'Supervisor - Decision Override_DE',
    'Inspection':'Inspection_DE',
    'InspectionVerdictInspect':'Inspection - Verdict – Inspect_DE',
    'InspectionDuration':'Inspection Duration_DE',
    'AllRoles' : 'All Roles_DE',
    'ActiveRoles' : 'Active Roles_DE',
    'InactiveRoles' : 'Inactive Roles_DE',
    'AllUsers' : 'All Users_DE',
    'ActiveUsers' : 'Active Users_DE',
    'InactiveUsers' : 'Inactive Users_DE',
    'AllApps' : 'All Apps_DE',
    'ActiveApps' : 'Active Apps_DE',
    'InactiveApps' : 'Inactive Apps_DE',
    'ReScan' : 'Rescan_DE',
    'Choose' : 'Choose_DE',
    'DecisionVerdictSuspect':'Decision - Verdict – Suspect_DE',
    'Knives':'Knives_DE',
    'Confirmed': 'Confirmed_DE',
    'Declared':'Declared_DE',
    'Dashboard':'Dashboard_DE',
    'ProfilerDashboard':'Profiler Dashboard_DE',
    'OperationalDashboard':'Operational Dashboard_DE',
    'DurationMins':'Duration (Mins)_DE',
    'DurationHrs':'Duration (Hrs)_DE',
    'HideRuler':'Hide_DE',
    'DeleteRuler': 'Delete_DE',
    'DuplicateAction': 'Duplicate Performed_DE',
    'profilerResultDashboard':'% of Cases for Screening & Cleared by Profiler – Last 30 Days Total and by Day_DE',
    'profilerResultSummary':'Red Cases and Final Verdicts – Summarised Last 30 Days_DE',
    'profilerVerdict':'Red Cases and Final Verdicts – Last 30 Days Total and by Day_DE',
    'ProfilerResultHeader':'Profiler Results Dashboard_DE',
    'imageLoadingError':'Unable to load the image. Please try again. If the problem persists, please send the Case back to your Supervisor._DE',
    'allowedImageFormats': 'Only PDF, PNG, JPEG, TIFF are allowed_DE',
    'OverAllRisk': 'Overall Risk_DE',
    'NoRulers': 'There are no rulers associated with this Case_DE',
    'Automatic':'Automatic_DE',
    'SaveInProgress' :'Save In Progress_DE',
    'PairingCase':'Pairing Case_DE',
    'Case Risk Profiler Result Updated': 'Case Risk Profiler Result Updated_DE',
    'Case Verdict Profiler Cleared':'Case Verdict Profiler Cleared_DE',
    'Sunday':'Sun_DE',
    'Monday':'Mon_DE',
    'Tuesday':'Tue_DE',
    'Wednesday':'Wed_DE',
    'Thursday':'Thu_DE',
    'Friday':'Fri_DE',
    'Saturday':'Sat_DE',
    'Jan':'Jan_DE',
    'Feb':'Feb_DE',
    'Mar':'Mar_DE',
    'Apr':'Apr_DE',
    'May':'May_DE',
    'Jun':'June_DE',
    'July':'July_DE',
    'Aug':'Aug_DE',
    'Sep':'Sep_DE',
    'Oct':'Oct_DE',
    'Nov':'Nov_DE',
    'Dec':'Dec_DE',
    'SelectBeginDate':'Select Begin Date_DE',
    'SelectEndDate':'Select End Date_DE',
    'ScanDetails':'Scan Details_DE',
    'Retry':'Retry_DE',
    'NoCasesAssigned':'There are currently no Cases assigned to you_DE',
    'scan attached':'Scan Attached_DE',
    'scan attach Failed':'Scan Attach Failed_DE'
};
