export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
    'Login': 'Login_FR',
    'UserId': 'User Id_FR',
    'EnterUserId': 'Please enter user id_FR',
    'EnterUserPassword': 'Please enter password_FR',
    'InvalidUserPassword': 'Invalid user name or password_FR',
    'Password': 'Password_FR',
    'RoleName': 'Role Name_FR',
    'Description': 'Description_FR',
    'Status': 'Status_FR',
    'NewRoleDescription': 'Role Description_FR',
    'CreateNewRole': 'Create Role_FR',
    'GeneralInformation': 'General Information_FR',
    'RoleNameDuplicate': 'Role name already exists._FR',
    'RoleMandatoryFields': 'All mandatory fields must be provided to create a case_FR',
    'RolesNotExist': 'There are no roles created in the system_FR',
    'Required': 'This is a required field_FR',
    'OnlyNumber': 'Please enter numeric value_FR',
    'EnterRoleName': 'Please Enter Role Name_FR',
    'RoleExists': '%0 already exists, duplicate names not allowed please enter another name_FR',
    'EnterRoleDescription': 'Please Enter Role Description_FR',
    'RoleCloseMessage': 'You are leaving the window without saving it_FR',
    'SureCloseMessage': 'Are you sure you want to leave?_FR',
    'LeaveWithoutSaveButton': 'Leave without save_FR',
    'BackToWindowButton': 'Back to window_FR',
    'CasesNotExist': 'There are no Cases available in the system._FR',
    'TimeZone': 'Time Zone_FR',
    'Currency': 'Currency_FR',
    'Language': 'Language_FR',
    'DateFormat': 'Date Format_FR',
    'TimeFormat': 'Time Format_FR',
    'PFRM10000': 'Role is created successfully._FR',
    'PFRM10001': 'Duplicate role. Role name should be unique._FR',
    'PFRM10002': 'Please provide all the required information for creating a role_FR',
    'PFRM10003': 'Role Format Error. Role name should be alphanumeric with no special characters._FR',
    'PFRM10004': 'Role data is invalid._FR',
    'PFRM10100': 'Error occured while saving the role. Please try again later and contact admin if error persists._FR',
    'PFRM10999': 'Unknown exception occured while saving the role. Please contact admin if error persists._FR',
    'PFRM40100': 'Database Error occured while getting the roles. Please try again later and contact admin if error persists._FR',
    'PFRM30999': 'Unknown exception occured while updating the role. Please contact admin if error persists._FR',
    'PFRM40999': 'Unknown exception occured while getting the roles. Please contact admin if error persists._FR',
    'PFRM30100': 'Database error while saving the roles_FR',
    'PFRM40000': 'Roles Details fetched successfully_FR',
    'SACM10000': 'Case is submitted successfully._FR',
    'SACM10002': 'Please provide all the required information for creating a case._FR',
    'SACM10003': 'Case Format Error. Please make sure all the case properties are in right format._FR',
    'SACM10004': 'Invalid case management data._FR',
    'SACM10100': 'Error occured while saving the case. Please try again later and contact admin if error persists._FR',
    'SACM10999': 'Unknown exception occured while saving the case. Please contact admin if error persists._FR',
    'SACM40100': 'Database Error occured while getting the cases. Please try again later and contact admin if error persists._FR',
    'SACM40000': 'Case Details fetched successfully_FR',
    'SACM40999': 'Unknown exception occured while getting the case. Please contact admin if error persists_FR',
    'PFAM10000': 'Application was submitted successfully_FR',
    'PFAM10002': 'Please provide all the required information for creating an Application._FR',
    'PFAM10003': 'Application Format Error. Please make sure all the application properties are in right format._FR',
    'PFAM10004': 'Invalid application data._FR',
    'PFAM10100': 'Error occured while saving the application. Please try again later and contact admin if error persists._FR',
    'PFAM10999': 'Unknown exception occured while saving the application. Please contact admin if error persists._FR',
    'PFAM40100': 'Database Error occured while getting the applications. Please try again later and contact admin if error persists._FR',
    'PFAM40000': 'Applications Details fetched successfully_FR',
    'PFAM40999': 'Unknown exception occured while getting the apps details. Please contact admin if error persists._FR',
    'PFCC40100': 'Database Error occured while getting the customers data. Please try again later and contact admin if error persists._FR',
    'PFCC40000': 'Customers Details fetched successfully_FR',
    'PFCC40999': 'Unknown exception occured while getting the customers details. Please contact admin if error persists._FR',
    'PFUM10000': 'User created successfully._FR',
    'PFUM10001': 'Duplicate User. User details should be unique._FR',
    'PFUM10002': 'Please provide all the required information for creating a user_FR',
    'PFUM10003': 'User Format Error. User name should be alphanumeric with no special characters._FR',
    'PFUM10004': 'User data is invalid._FR',
    'PFUM10100': 'Error occured while saving the user. Please try again later and contact admin if error persists._FR',
    'PFUM10999': 'Unknown exception occured while saving the user. Please contact admin if error persists._FR',
    'PFUM40100': 'Database Error occured while getting the users. Please try again later and contact admin if error persists._FR',
    'PFUM40999': 'Unknown exception occured while getting the users. Please contact admin if error persists._FR',
    'PFUM40000': 'Users Details fetched successfully_FR',
    'PFUM30000': 'User updated successfully._FR',
    'PFUM30002': 'Please provide all the required information for updating a user_FR',
    'PFUM30003': 'User Format Error. User name should be alphanumeric with no special characters._FR',
    'PFUM30004': 'User data is invalid._FR',
    'PFUM30100': 'Error occured while saving the user. Please try again later and contact admin if error persists._FR',
    'PFUM30999': 'Unknown exception occured while saving the user. Please contact admin if error persists._FR',
    'PFUM40004': 'Error occured while getting the user details_FR',
    'PFSM40000': 'Successful Security _FR',
    'PFSM40002': 'Mandatory information missing_FR',
    'PFSM40004': 'Security data invalid_FR',
    'ContainerID': 'Container ID_FR',
    'Weight': 'Weight_FR',
    'Length': 'Length_FR',
    'From': 'From_FR',
    'Country': 'Country_FR',
    'OriginPort':'Origin Port_FR',
    'DestinationPort':'Destination Port_FR',
    'To': 'To_FR',
    'Company': 'Company_FR',
    'CreateCaseButton': 'Create Case_FR',
    'CreateCaseSuccess': 'A new case has been submitted_FR',
    'Alert': 'Alert_FR',
    'Ok': 'OK_FR',
    'Reset': 'Reset_FR',
    'EnterContainerId': 'Please enter container ID_FR',
    'EnterCompany': 'Please enter company_FR',
    'ContainerLength': 'Container length should not be more than 50_FR',
    'ContainerWeight': 'Container weight should not be more than 100_FR',
    'NotAuthorized': 'You are not authorized to perform this action._FR',
    'DefaultError': 'Error occured while performing the current operation. Please try again later and contact admin if error persists._FR',
    'RightsReserved': 'All rights reserved_FR',
    'Settings': 'Settings_FR',
    'AppsNotAssigned': 'You have not been assigned any applications. Please contact admin_FR',
    'NotAssignedApps': 'You have not assigned any Applications._FR',
    'Create': 'Create_FR',
    'Cancel': 'Cancel_FR',
    'CreateRoleQuestion': 'Do you want to create the role?_FR',
    'Yes': 'Yes_FR',
    'No': 'No_FR',
    'General': 'General_FR',
    'Users': 'Users_FR',
    'Roles': 'Roles_FR',
    'Applications': 'Applications_FR',
    'UserName': 'User Name_FR',
    'Apps': 'Applications_FR',
    'LocalSettings': 'Local Settings_FR',
    'RegionalSettings': 'Regional Settings_FR',
    'MeasureUnit': 'Measure Unit_FR',
    'ChangesSave': 'Changes saved successfully_FR',
    'NotSavedChanges': 'Warning: You have not saved your changes._FR',
    'LeaveMessage': 'Are you sure you want to leave?_FR',
    'RoleInactiveMessage1': 'Warning: You have made the role inactive, there are users assigned to this role._FR',
    'RoleInactiveMessage2': 'The users will not be able to view this role once deactivated._FR',
    'RoleInactiveLeaveMessage': 'Are you sure you want to deactivate the role?_FR',
    'RoleCreated': 'Role created_FR',
    'FilterBy': 'Filter By_FR',
    'Save': 'Save_FR',
    'OrgId': 'Org ID_FR',
    'OrgIdLabel': 'Org ID_FR',
    'fullName': 'Full Name_FR',
    'Id': 'ID_FR',
    'AccountCreate': 'Account Created:_FR',
    'Email': 'Email_FR',
    'Telephone': 'Telephone_FR',
    'EmpStatus': 'Employment Status_FR',
    'Position': 'Position_FR',
    'Mobile': 'Mobile_FR',
    'AddNewUser': 'Add New User_FR',
    'AddNewRole': 'Add New Role_FR',
    'CreateUserProfile': 'Add New User_FR',
    'NoUserFound': 'No User Found_FR',
    'NoResultFound': 'No Result Found_FR',
    'NotAssignedRoles': 'You have not assigned any Roles._FR',
    'CreateUserQuestion': 'Do you want to create the user?_FR',
    'SaveMessageQuestion': 'Do you want to save the changes?_FR',
    'InvalidEmail': 'Email is invalid_FR',
    'InvalidTelephone': 'Telephone is invalid_FR',
    'InvalidMobile': 'Mobile number is invalid_FR',
    'GeneralSettings': 'General Settings_FR',
    'User': 'Users_FR',
    'MappedRoles': 'Mapped Roles_FR',
    'AppAdded': 'App Added_FR',
    'AppPublished': 'App Published_FR',
    'AppLastUpdated': 'App Last Updated_FR',
    'AppVersion': 'Version_FR',
    'Type': 'Type_FR',
    'Category': 'Category_FR',
    'Arrivals': 'Arrivals_FR',
    'MyCases': 'My Cases_FR',
    'CreateNewCase': 'Create New Case_FR',
    'CreateCase': 'Create a case_FR',
    'Search': 'Search_FR',
    'ClearAllSelected': 'Clear All Selected_FR',
    'ScanAllSelected': 'Scan All Selected_FR',
    'CancelAllSelected': 'Cancel All Selected_FR',
    'CaseId': 'Case Id_FR',
    'CaseIdText': 'Case Id_FR:',
    'CASEID': 'FR_CASEID_FR',
    'StartSearching': 'Start Searching_FR',
    'UpdatedDate': 'UpdatedDate_FR',
    'ControlCenterCaseId': 'Case Id_FR',
    'ContainerId': 'Container Id_FR',
    'Container': 'Container_FR',
    'HSCode': 'Harmonised System Code_FR',
    'HSCodes': 'Harmonised System Codes_FR',
    'HSCodesText': 'Harmonised System Codes_FR',
    'hscodeToolTip': 'Mutiple HSCodes should be seperated by a single comma_FR',
    'DateCreated': 'Date Created_FR',
    'LastModifiedDate': 'Last Modified Date_FR',
    'LastModified': 'Last Modified_FR',
    'ShippingCompany': 'Shipping Company_FR',
    'DateOfArrival': 'Date of Arrival_FR',
    'ArrivalDateSearch': 'Arrival Date_FR',
    'ShipId': 'Ship Id_FR',
    'ShipIdText' : 'Ship Id_FR',
    'InvalidEntry': 'Entry does not match validation criteria, please edit_FR',
    'InvalidShipEntry': 'Entry does not match validation criteria. Ship ID Should be IMO9176187 Format)._FR',
    'InvalidHsCodeEntry': 'Entry does not match validation criteria. HS Code Should be Numeric._FR',
    'InvalidWeightEntry': 'Entry does not match validation criteria. Weight should be in kgs (Up to two Decimals)._FR',
    'InvalidContainerIDEntry': 'Entry does not match validation criteria. Container ID should be Alpha-numeric._FR',
    'MyDrafts': 'My Drafts_FR',
    'AllCases': 'All Cases_FR',
    'VehicleInformation': 'Vehicle Information_FR',
    'PlateNumber': 'Plate Number_FR',
    'VehicleMake': 'Vehicle Make_FR',
    'DriverName': 'Driver Name_FR',
    'VehicleCompany': 'Vehicle Company_FR',
    'VehicleModal': 'Vehicle Model_FR',
    'DriverLicense': 'Driver License_FR',
    'ContainerInformation': 'Container Information_FR',
    'CaseLastUpdated': 'Last Updated On:_FR',
    'CaseLastUpdatedBy': 'Last Updated By:_FR',
    'ManualCaseCreation': 'Create a case_FR',
    'CaseDetails': 'Case Details_FR',
    'QueryBuilder': 'Query Builder_FR',
    'SearchCases': 'Search Cases_FR',
    'CaseStatus': 'Status_FR',
    'CaseStatusText': 'Status_FR:',
    'Clear': 'Clear_FR',
    'Scan': 'Scan_FR',
    'cancelCase': 'Cancel This Case_FR',
    'decideLater': 'Decide Later_FR',
    'CargoType': 'Cargo Type:_FR',
    'ExpandAllCasePanels': 'Expand All_FR',
    'CollapseAllCasePanels': 'Collapse All_FR',
    'CaseInformation': 'Case Information_FR',
    'caseInfoActions': 'More Actions_FR',
    'sender': 'Sender_FR',
    'SenderAddress': 'Sender Address_FR',
    'CaseFrom': 'Origin Country_FR',
    'CaseTo': 'Destination Country_FR',
    'ArrivalDate': 'Date of Arrival_FR',
    'ArrivalDateText': 'Date of Arrival_FR',
    'OverAllWeight': 'Overall Weight(kgs)_FR',
    'OverAllWeightText':'Overall Weight_FR',
    'Notes': 'Notes_FR',
    'NotesText': 'Notes_FR:',
    'ShipInfomation': 'Ship Information_FR',
    'ShipCompany': 'Shipping Company_FR',
    'Containers': 'Container ID_FR',
    'Contact': 'Contact_FR',
    'Nationality': 'Nationality_FR',
    'Attachments': 'Attachments_FR',
    'AddAttachments': 'Add Attachments_FR',
    'Update': 'Update_FR',
    'SaveAsDraft': 'Save As Draft_FR',
    'UpdateDraft': 'Update Draft_FR',
    'CaseDraftValidationMessage': 'Case cannot be saved as draft. Please make sure to fill in the following fields: Arrival Date, Container ID and Destination Country._FR',
    'Delete': 'Delete_FR',
    'Close': 'Close_FR',
    'DeleteAllSelected': 'Delete Selected_FR',
    'DeleteCaseQuestion': 'Are you sure you would like to delete the following case(s)?_FR',
    'ClearAllSelectedQuestion': 'Are you sure you would like to Clear the following case(s)?_FR',
    'CancelAllSelectedQuestion': 'Are you sure you would like to Cancel the following case(s)?_FR',
    'ScanAllSelectedQuestion': 'Are you sure you would like to Scan the following case(s)?_FR',
    'InspectAllSelectedQuestion': 'Are you sure you would like to Inspect the following case(s)?_FR',
    'SuspectAllSelectedQuestion': 'Are you sure you would like to Suspect the following case(s)?_FR',
    'ClearAllSelectedCasesText': 'We are going to clear following cases:_FR',
    'SuspectAllSelectedCasesText': 'We are going to suspect following cases:_FR',
    'InspectAllSelectedCasesText': 'Please select an Inspection Type for following cases:_FR',
    'ScanAllSelectedCasesText': 'We are going to scan following cases:_FR',
    'RescanAllSelectedCasesText': 'We are going to rescan the following Cases_FR',
    'FailedCaseListText': 'The following cases have failed:_FR',
    'AwaitingScreeningSelectedCasesText': 'We are about to change the status of following cases to Awaiting Screening:_FR',
    'SaveChanges': 'Save Changes_FR',
    'ClearCaseQuestion': 'Are you sure you want to clear?_FR',
    'ScanCaseQuestion': 'Are you sure you want to send to scan?_FR',
    'SuspectCase': 'Are you sure you want to set the case as Suspect?_FR',
    'InspectCase': 'Are you sure you want to Inspect the Case?_FR',
    'ReScanRequest': 'Are you sure to request for Rescan of the case?_FR',
    'CancelCaseQuestion': 'Are you sure yu want to Cancel ?_FR',
    'UploadAttachment': 'Upload Attachment_FR',
    'AttachmentInfo': 'Please fill the following information for this attachment:_FR',
    'Title': 'Title_FR',
    'AttachmentDescription': ' is selected as an attachement of this case._FR',
    'Upload': 'Upload_FR',
    'FieldsInfoMissing': '%0 field(s) information is missing_FR',
    'AddNewAttachment': 'Add New Attachment_FR',
    'Edit': 'Edit_FR',
    'CharactersLeft': 'character(s) left_FR',
    'ConfirmAttachmentsDelete': 'Please confirm following attachments will be deleted:_FR',
    'DeleteAttachments': 'Delete Attachments_FR',
    'Actions': 'Actions_FR',
    'ManageCases': 'Manage Cases_FR',
    'Suspect': 'Suspect_FR',
    'Activity': 'Activity_FR',
    'Refresh': 'Refresh_FR',
    'ViewCaseDetails': 'View Case Details_FR',
    'Screening': 'Screening_FR',
    'Override': 'Override_FR',
    'Inspect': 'Inspect_FR',
    'TrailerInformation': 'Trailer Information_FR',
    'AssessmentImages': 'Assessment Images_FR',
    'ImageAssessmentVerdict': 'Image Assessment Verdict_FR',
    'InspectionEvidence': 'Inspection Evidence_FR',
    'InspectionVerdict': 'Inspection Verdict_FR',
    'Displaying': 'Displaying_FR',
    'of': 'of_FR',
    'AwaitingScreening': 'Awaiting Screening_FR',
    'AwaitingScan': 'Awaiting Scan_FR',
    'Awaiting Screening': 'Awaiting Screening_FR',
    'Awaiting Scan': 'Awaiting Scan_FR',
    'Cleared': 'Cleared_FR',
    'Cancelled': 'Cancelled_FR',
    'Draft': 'Draft_FR',
    'Deleted': 'Deleted_FR',
    'AwaitingAssessment': 'Awaiting Assessment_FR',
    'AssessmentInProgress': 'Assessment In Progress_FR',
    'AwaitingReAssessment': 'Re-Assessment Requested_FR',
    'Awaiting Assessment': 'Awaiting Assessment_FR',
    'Assessment InProgress': 'Assessment In Progress_FR',
    'Awaiting Re-Assessment': 'Awaiting Re-Assessment_FR',
    'Emergency': 'Emergency_FR',
    'InspectionRequested': 'Inspection Requested_FR',
    'AwaitingInspection': 'Awaiting Inspection_FR',
    'InspectionInProgress': 'Inspection In Progress_FR',
    'InspectionCleared': 'Inspection Cleared_FR',
    'ReScanRequested': 'Rescan Requested_FR',
    'AssessmentCleared': 'Assessment Cleared_FR',
    'Inspection Requested': 'Inspection Requested_FR',
    'Awaiting Inspection': 'Awaiting Inspection_FR',
    'Inspection in Progress': 'Inspection In Progress_FR',
    'Inspection Cleared': 'Inspection Cleared_FR',
    'Re-Scan Requested': 'Rescan Requested_FR',
    'Assessment Cleared': 'Assessment Cleared_FR',
    'Priority': 'Priority_FR',
    'Hold': 'Hold_FR',
    'EmptyMessage': 'There are no Cases that match your query_FR',
    'ClearCase': 'Clear Case_FR',
    'SuspectCaseId': 'Suspect Case: _FR',
    'ReScanCaseId': 'The following case will be Rescanned_FR',
    'Loading': 'Loading...._FR',
    'ImageLoading': 'Image Loading...._FR',
    'ApplicationLoading': 'Application Loading..._FR',
    'RequestCaseReInspection': 'Request Inspection of Case: _FR',
    'RequestCaseReAssess': 'Request Case Re-Assessment _FR',
    'EmptyReport': 'There are no finding associated to the report_FR',
    'ImageValidaitonMessage': 'No cases to be assessed_FR',
    'AssessmentSummary': 'Assessment Summary*_FR',
    'LoadNextCase': 'Load Next Case_FR',
    'MoreActions': 'MORE ACTIONS_FR',
    'RequestReAssessment': 'Request Reassessment_FR',
    'FitToWindow': 'Fit To Window_FR',
    'ImageSaveMessage': 'Would you like to save these changes as a new view?_FR',
    'NoResults': 'No Results Found_FR',
    'NoResultsMessage': 'Try widening your search_FR',
    'HSCodeGoodsType': 'HS Code/Goods Type_FR',
    'LeftorRight': 'Left Or Right_FR',
    'ToporBottom': 'Top Or Bottom_FR',
    'FrontorBack': 'Front or Back_FR',
    'Left': 'Left_FR',
    'Right': 'Right_FR',
    'Top': 'Top_FR',
    'Bottom': 'Bottom_FR',
    'Front': 'Front_FR',
    'Back': 'Back_FR',
    'ImageAnalyzer': 'Image Analyser_FR',
    'Brightness': 'Brightness_FR',
    'Contrast': 'Contrast_FR',
    'DeleteFinding': 'Are you sure you want to delete the finding?_FR',
    'DeleteFindingHeader': 'Delete Finding_FR',
    'NoFindings': 'There are no findings associated with this Case._FR',
    'Finding_Category': 'Category_FR',
    'Finding_GoodsType': 'Goods Type/ HS Code_FR',
    'Finding_Description': 'Description_FR',
    'RequestReAssessmentVerdict': 'Request Reassessment_FR',
    'RequestReScanVerdict': 'Request Rescan_FR',
    'SuspectVerdict': 'Suspect_FR',
    'InspectVerdict': 'Inspect_FR',
    'ClearVerdict': 'Clear_FR',
    'ActionsVerdict': 'Actions_FR',
    'Finding_Declare': 'Declare_FR',
    'Finding_Declared': 'Declared_FR',
    'Finding_Confirm': 'Confirm_FR',
    'Finding_Confirmed': 'Confirmed_FR',
    'RulerDeleteQuestion': 'Are you sure you want to delete the Ruler?_FR',
    'RulerMark': 'Delete Ruler_FR',
    'AddRuler': 'Add Ruler_FR',
    'RulerCreationErrorMessage': 'Ruler Mark not long enough to be saved_FR',
    'ColorPreset': 'Color Presets_FR',
    'CaseLoading': 'Case Loading..._FR',
    'RiskRating': 'Risk Rating_FR',
    'LastUpdatedDate': 'Last Modified_FR',
    'LastUpdated': 'Last Modified Date_FR',
    'clearedCaseNote1': 'Cases available for_FR',
    'clearedCaseNote2': ' hours from cleared date_FR',
    'GridClearCaseLoading': 'Loading Clear Case details_FR',
    'PhysicalInspection': 'Physical Inspection_FR',
    'ClearCases': 'Clear Cases_FR',
    'Confirm': 'Confirm_FR',
    'Comments': 'Comments_FR',
    'PhysicalVerdict': 'Physical_FR',
    'SelectInspectionType': '- Please select an Inspection Type_FR',
    'SendToScreen': 'Send to Screen_FR',
    'AwaitingInspectionCases': 'Awaiting Inspection Cases_FR',
    'CreateNewView': 'Create New View_FR',
    'NoOfFindings': 'No of Findings_FR',
    'NoOfFindingsTooltip': 'No of Findings for the Case_FR',
    'ProfilerSettings': 'Profiler Settings_FR',
    'ReScanRequestText': 'Rescan Request_FR',
    'BackToList': 'Back To List_FR',
    'FindingsAndVerdict': 'Verdict_FR',
    'DCSettings': 'Decision Center Settings_FR',
    'ThresholdNumberRangeMessage': 'Please enter a number between 0 and 100_FR',
    'ThresholdNumberRangeMessageDC': 'Please enter a number between 0 and 10000_FR',
    'ThresholdTitleMessage': 'Changing the below thresholds will impact the overall Case Risk Score. All changes to these fields are recorded and audited. Please be aware that raising the threshold value results in higher risk items being passed through, and lowering the threshold value results in lower risk items being assessed._FR',
    'Threshold': 'Threshold_FR',
    'RiskCategory': 'Risk Category_FR',
    'FindingsCategory': 'Findings Category_FR',
    'InspectionType': 'Inspection Type_FR',
    'DiscardAndLeave': 'Discard And Leave_FR',
    'StayInApp': 'Stay in app_FR',
    'DiscardMessage': 'Would you like to leave the app and discard the changes?_FR',
    'AddNewFinding': 'Add New Finding_FR',
    'EvidenceAttached': 'Evidence Attached_FR',
    'ConfirmNewFinding': 'The following Finding will be created, please confirm._FR',
    'RiskLevel': 'Risk Level_FR',
    'RuleCategory': 'Category_FR',
    'CategoryScore': 'Score_FR',
    'ThresholdBreach': 'Breach_FR',
    'CaseRiskScore': 'Case Risk Score_FR',
    'CategoryScores': 'Category Scores_FR',
    'CreateFinding': 'Create a new Finding_FR',
    'CreateRuler': 'Create a new Ruler Mark_FR',
    'CaseTimeline': 'Case Timeline_FR',
    'batchId': 'Batch Id_FR',
    'containerIds': 'Container Id_FR',
    'scanTime': 'Scan Time_FR',
    'NoFilteredCases': 'There are no Cases available for inspection._FR',
    'NoFilteredInspectionCases': 'There are no Cases of ' + 'xxxx' + ' Inspection Type. Please clear filter or select another Inspection type._FR',
    'NoFilteredFindingCases': 'There are no Cases of ' + 'xxxx' + ' Findings Category. Please clear filter or select another Findings Category._FR',
    'RAPPathway': 'RAP Pathway_FR',
    'RapColour': 'RAP Colour_FR',
    'RapColourStatus': 'Initial Case status_FR',
    'MinRapScore': 'Minimum RAP Score_FR',
    'MaxRapScore': 'Maximum RAP Score_FR',
    'rapValidMessage': 'Please enter valid range number_FR',
    'ScanId': 'Scan Id_FR',
    'ScanDateTime': 'Date & Time Scan Created_FR',
    'SelectScanner': 'Select Scanner_FR',
    'FilterTable': 'Filter Table_FR',
    'ApplyFilter': 'Apply Filter_FR',
    'LoadScanner': 'Load Scanner_FR',
    'ChangeScanner': 'Change Scanner_FR',
    'ScanDate': 'Scan Date_FR',
    'AssociationStatus': 'Association Status_FR',
    'RiskScore': 'Risk Score_FR',
    'DCSetting': 'DC Settings_FR',
    'RapErrorMessage': 'Invalid value entered in Min/Max RAP Score field_FR',
    'English': 'English_FR',
    'French': 'French_FR',
    'German': 'German_FR',
    'English_FR': 'English',
    'French_FR': 'French',
    'German_FR': 'German',
    'AwaitingProfiling': 'Awaiting Profiling_FR',
    'CurrentStatus': 'Current Status_FR',
    'Ship': 'Shipping Information_FR',
    'DeparturePort': 'Departure Port_FR',
    'DepartureDate': 'Departure Date_FR',
    'MatchCaseHeaderText': 'Display Matching Case_FR',
    'MatchCaseInfoText': 'The following case matches the case information submitted. Can you either confirm that these are the same cases or that they are different cases_FR',
    'ShippingNationality': 'Nationality_FR',
    'ShippingContact': 'Contact_FR',
    'SerialNumber': 'Serial Number_FR',
    'Manufacturer': 'Manufacturer_FR',
    'DeviceID': 'Device Id_FR',
    'Display': 'Display_FR',
    'LocationSetting': 'Locations_FR',
    'ModelName': 'Model Name_FR',
    'Latitude': 'Location.Latitude_FR',
    'Longitude': 'Location.Longitude_FR',
    'Location': 'Location_FR',
    'AssignedLicense': 'License_FR',
    'NoLicense': 'No Device License Available_FR',
    'NoUserLicense': 'No User License Available_FR',
    'DeviceSetting': 'Device Settings_FR',
    'AssessmentSummaryText': 'Assessment Summary_FR',
    'VerdictStatus': 'Verdict Status_FR',
    'operationalDashboard': 'Operational Dashboard_FR',
    'AssignLicense': 'License_FR',
    'Active': 'Active_FR',
    'Inactive': 'Inactive_FR',
    'None': 'None_FR',
    'Disabled': 'Disabled_FR',
    'ToggleLicenseFailure': 'Failure to Apply License_FR',
    'TargetImageAccessed': 'Target Images Assessed (per User per Hour)_FR',
    'FindingNumber': 'Finding Number_FR',
    'caseDetailId': 'Id_FR',
    'FindingAttachments': 'Finding Attachments_FR',
    'FileName': 'File Name_FR',
    'FileData': 'File Data_FR',
    'FileDescription': 'File Description_FR',
    'SelectedLocation': 'Location_FR',
    //dashboard translate constant
    'KPIS':'KPIS_FR',
    'ScreenedAssessed':'Screened & Assessed_FR',
    'Screened':'Screened_FR',
    'Inspected':'Inspected_FR',
    'Suspected':'Suspected_FR',
    'TotalAssessments':'Total Assessments_FR',
    'Target':'TARGET_FR',
    'Actual':'ACTUAL_FR',
    'Name':'Name_FR',
    'ShowHide':'Show/Hide_FR',
    'Green':'Green_FR',
    'Amber':'Amber_FR',
    'Red':'Red_FR',
    'Blue':'Blue_FR',
    'ImageAssesmentTitle':'Image Assessment Compared to Target_FR',
    'Today':'Today_FR',
    'Last24':'Last 24 HRS_FR',
    'ActualLegend':'Actual_FR',
    'TargetLegend':'Target_FR',
    'ProfilerchartHeader':'Profiler Resource Forecast Chart_FR',
    'TotalChart':'Total Chart_FR',
    'TotalExpected':'Total Expected_FR',
    'TotalProfiled':'Total Profiled_FR',
    'RapColorChart':'RAP Colour Chart_FR',
    'ProfiledCases':'Profiled Cases_FR',
    'ExpectedCase':'Expected Case_FR',
    'TotalProfiledCases':'Total Profiled Cases_FR',
    'TotalExpectedCases' : 'Total Expected Cases_FR',
    'SecureRedirection': 'Redirecting to Secure Login Page..._FR',
    'UnauthorisedAccess': 'Unauthorised Access_FR',
    'AdminContactMessage': 'You are not a registered user or your account does not have a valid licence. Please contact the system administrator._FR',
    'Attached':'Attached_FR',
    'UserTimeline':'User_FR',
    'NoRecordsFound':'No records found_FR',
    'NoAttachmentsFound':'No attachments found_FR',
    'ScanToColourMapping' :'Convert Scan to Colour Mapping_FR',
    'ScanToOriginalGreyscale': 'Convert Scan to original Greyscale_FR',
    'Organic': 'Organic_FR',
    'NonOrganic': 'Non-Organic_FR',
    'Metal': 'Metal_FR',
    'ShowFindings' :'Show Findings for this scan_FR',
    'HideFindings' :'Hide Findings for this scan_FR',
    'ShowRulers' :'Show Rulers for this scan_FR',
    'HideRulers' :'Hide Rulers for this scan_FR',
    'Effects':'Effects_FR',
    'Vizual':'ViZual_FR',
    'FitToView': 'Fit view_FR',
    'UserLoading': 'Loading Users..._FR',
    'UserDetailLoading': 'Loading User Details_FR',
    'SettingsLoading': 'Loading Settings..._FR',
    'SaveSettingsLoading': 'Save Settings_FR',
    'GeneralSettingsHeader': 'General Settings_FR',
    'UsersUpdating': 'Updating User..._FR',
    'UsersSaving': 'Saving User..._FR',
    'RolesUpdating': 'Updating Role..._FR',
    'RolesSaving': 'Saving Role..._FR',
    'RoleDetailLoading': 'Loading Role Details..._FR',
    'RoleLoading': 'Loading Roles..._FR',
    'SessionTimeout':'Session has expired_FR',
    'SessionExpireMessage':'You have been logged out due to inactivity._FR',
    'SessionRoute':'Click here to login_FR',
    'Note':'Note_FR',
    'ApplDetailLoading': 'Loading Application Details..._FR',
    'AppInformation': 'Applications Information_FR',
    'AppsUpdating': 'Updating Application..._FR',
    'ProfilerInfo' : 'Profiler Information_FR',
    'ProfilerSettingsLoading': 'Loading Profiler Settings..._FR',
    'ProfilerSettingsSaving': 'Saving Profiler Settings..._FR',
    'RAPPathwayInfo': 'RAP Pathway Information_FR',
    'RAPPathwayLoading': 'Loading RAP Pathway Settings..._FR',
    'RAPPathwaySaving' :'Saving RAP Pathway Settings..._FR',
    'Parameter': 'Parameter_FR',
    'Value': 'Value_FR',
    'DeviceLicenseInfo' : 'Device License Information_FR',
    'DeviceDetailLoading': 'Loading Device Details..._FR',
    'DeviceDetailSaving' :'Saving Device Details..._FR',
    'DecisionCentre':'Decision Centre_FR',
    'DecisionCenterInfo' : 'Decision Center Settings_FR',
    'DecisionCenterLoading': 'Loading Decision Center Settings..._FR',
    'DecisionCenterSaving' :'Saving Decision Center Settings..._FR',
    'LocationID' : 'Location Id_FR',
    'LocationName' : 'Location Name_FR',
    'LocationCode' : 'Location Code_FR',
    'OperationalDashBoardSetting' : 'Operational Dashboard Settings_FR',
    'Detail' : 'Detail_FR',
    'Timeline' : 'Timeline_FR',
    'SavedViews' : 'Saved Views_FR',
    'Verdict' : 'Verdict_FR',
    'LogOut': 'Log out_FR',
    'CategoryType': 'Category Type_FR',
    'NIIStatus' : 'For NII -Status_FR',
    'RAPSelectedStatus' : 'For (RAD/NUC, De-Stuff, Canine) - Status_FR',
    'Source' : 'Source_FR',
    'ImageAssessment' : 'Image Assessment_FR',
    'Findings' : 'Findings_FR',
    'Finding': 'Finding_FR',
    'Action': 'Action_FR',
    'ApprovalRequest' : 'Approval Request_FR',
    'ApprovalRequestType' : 'Approval Request Type_FR',
    'HsCodeOrGoodsType' : 'HSCode / Goods Type_FR',
    'CaseCreation' : 'Case Creation_FR',
    'Profiler' : 'Profiler_FR',
    'View': 'View_FR',
    'Ruler' : 'Ruler_FR',
    'InspectorAssigned' : 'Inspector Assigned_FR',
    'InspectorVerdict' : 'Inspector Verdict_FR',
    'CasePriority' : 'Case Priority_FR',
    'CaseHold' : 'Case Hold_FR',
    'RiskColor' : 'Risk Color_FR',
    'Date' : 'Date_FR',
    'Manual' : 'Manual_FR',
    'Attachment': 'Attachment_FR',
    'UserLabel' : 'User_FR',
    'Evidence' : 'Evidence_FR',
    'AssignToSelf' : 'Assign To Self_FR',
    'Approval' : 'Approval_FR',
    'EnterContainerIDLabel' : 'Enter Container ID_FR',
    'EnterContainerIDNumber' : 'Enter Container ID Number_FR',
    'CorsysScanId' : 'CORSYS Scan Id_FR',
    'FindCase' : 'Find Case_FR',
    'PairCase' : 'Pair Case_FR',
    'Pair':'Pair_FR',
    'NoCaseFound' : 'No case found with this Container ID_FR',
    'CheckCase' : 'Please double check the number is correct or create a new case._FR',
    'ZoomIn' : 'zoom+_FR',
    'ZoomOut' : 'zoom-_FR',
    'DisplayOn' : 'Display On_FR',
    'DisplayOff' : 'Display Off_FR',
    'AddMark' : 'Add Mark_FR',
    'SaveComment' : 'Save Comment_FR',
    'SelectFromList' : 'Select from list_FR',
    'CancelCase' : 'Cancel the Case_FR',
    'Submit': 'Submit_FR',
    'Leave' : 'Leave_FR',
    'Assessment' : 'Assessment_FR',
    'RulerId' : 'Ruler Id_FR',
    'Shapes' : 'Shapes_FR',
    'AssessmentDetails' : 'Assessment Details_FR',
    'Comment': 'Comments_FR',
    'ScanAssociationFailed' : 'The Scan has failed to associate with the case, please try again_FR',
    'Success' : 'Success_FR',
    'StatusUpdated' : 'Status Updated_FR',
    'InspectCaseText' : 'Inspect Case_FR',
    'SuspectCaseText' : 'Suspect Case_FR',
    'VerdictClearCase' : 'Verdict - Clear Case_FR',
    'VerdictInspectCase' : 'Verdict - Inspect Case_FR',
    'VerdictSuspectCase' : 'Verdict - Suspect Case_FR',
    'UploadEvidence' : 'Upload Evidence_FR',
    'VerdictCase' : 'Verdict: Case_FR',
    'SaveFinding' : 'Save Finding_FR',
    'LocationTitle':'Select a location_FR',
    'Heroin':'Heroin_FR',
    'Cocaine':'Cocaine_FR',
    'Marijuana':'Marijuana_FR',
    'Guns':'Guns_FR',
    'Knives':'Knives_FR',
    'weapons':'Weapons_FR',
    'drugs':'Drugs_FR',
    'Destuff':'De-stuff_FR',
    'Canine':'Canine_FR',
    'RADNUC':'RAD/NUC_FR',
    'undeclared':'Undeclared_FR',
    'SupervisorCaseCleared':'Supervisor - Case Cleared_FR',
    'RapSelected':'Rap Selected_FR',
    'ScanAssociated':'Scan – Scan Associated_FR',
    'AnalyserReAssessment':'Analyser - Re-assessment_FR',
    'AnalyserfindingCreated':'Analyser Findings - Created_FR',
    'AnalyserfindingUpdated':'Analyser Findings - Updated_FR',
    'AnalyserfindingDeleted':'Analyser Findings - Deleted_FR',
    'AnalyserRulersDeleted':'Analyser Rulers - Deleted_FR',
    'AnalyserRulersUpdated':'Analyser Rulers - Updated_FR',
    'AnalyserRulersCreated':'Analyser Rulers - Created_FR',
    'AnalyserViewsCreated':'Analyser Views - Created_FR',
    'AnalyserViewsUpdated':'Analyser Views - Updated_FR',
    'AnalyserVerdictCleared':'Analyser Verdict - Cleared_FR',
    'AnalyserVerdictSuspect':'Analyser Verdict - Suspect_FR',
    'AnalyserVerdictInspect':'Analyser Verdict - Inspect_FR',
    'SupervisorRescanRequestApproval':'Supervisor - Rescan Re-Request Approval_FR',
    'SupervisorFlagHoldOnHold':'Supervisor - Flag – Hold – On Hold_FR',
    'SupervisorFlagHoldRemoved':'Supervisor - Flag – Hold – Removed_FR',
    'SupervisorFlagPriorityCase':'Supervisor - Flag – Priority – Case Prioritized_FR',
    'SupervisorFlagPriorityRemoved':'Supervisor - Flag – Priority – Removed_FR',
    'InspectionInspectorAssignedCase':'Inspection - Inspector Assigned_FR',
    'InspectionVerdictCleared':'Inspection - Verdict – Cleared_FR',
    'InspectionVerdictSuspect':'Inspection - Verdict – Suspect_FR',
    'InspectionVerdictAddNewFinding':'Inspection - Verdict – Add New Finding_FR',
    'InspectionVerdictEvidence':'Inspection - Verdict – Evidence_FR',
    'InspectionFindingsDeleted':'Inspection – Findings – Deleted_FR',
    'InspectionFindingsUpdated':'Inspection – Findings – Updated_FR',
    'InspectionFindingsCreated':'Inspection – Findings – Created_FR',
    'InspectionRulersUpdated':'Inspection – Rulers – Updated_FR',
    'InspectionRulersDeleted':'Inspection – Rulers – Deleted_FR',
    'ManualCaseCreatedFileAttachment':'Manual Case Created – File Attachment_FR',
    'ProfilerResult':'Profiler Result_FR',
    'ManualCaseCreated':'Manual Case Created_FR',
    'SupervisorDeStuffInspect':'Supervisor -De-Stuff- Inspect_FR',
    'SupervisorRADInspect':'Supervisor -RAD/NUC- Inspect_FR',
    'SupervisorCanineInspect':'Supervisor -Canine- Inspect_FR',
    'SupervisorNIIScan':'Supervisor - NII - Scan_FR',
    'AnalyserInspect':'Analyser - Inspect_FR',
    'AnalyserReScan':'Analyser Rescan_FR',
    'InspectionRulersCreated':'Inspection – Rulers – Created_FR',
    'SupervisorInspectionApproved':'Supervisor - Inspection Approved – Inspect_FR',
    'SupervisorDecisionOverride':'Supervisor - Decision Override_FR',
    'Inspection':'Inspection_FR',
    'InspectionVerdictInspect':'Inspection - Verdict – Inspect_FR',
    'InspectionDuration':'Inspection Duration_FR',
    'AllRoles' : 'All Roles_FR',
    'ActiveRoles' : 'Active Roles_FR',
    'InactiveRoles' : 'Inactive Roles_FR',
    'AllUsers' : 'All Users_FR',
    'ActiveUsers' : 'Active Users_FR',
    'InactiveUsers' : 'Inactive Users_FR',
    'AllApps' : 'All Apps_FR',
    'ActiveApps' : 'Active Apps_FR',
    'InactiveApps' : 'Inactive Apps_FR',
    'ReScan' : 'Rescan_FR',
    'Choose' : 'Choose_FR',
    'DecisionVerdictSuspect':'Decision - Verdict – Suspect_FR',
    'Confirmed': 'Confirmed_FR',
    'Declared':'Declared_FR',
    'Dashboard':'Dashboard_FR',
    'ProfilerDashboard':'Profiler Dashboard_FR',
    'OperationalDashboard':'Operational Dashboard_FR',
    'DurationMins':'Duration (Mins)_FR',
    'DurationHrs':'Duration (Hrs)_FR',
    'HideRuler':'Hide_FR',
    'DeleteRuler': 'Delete_FR',
    'DuplicateAction': 'Duplicate Performed_FR',
    'profilerResultDashboard':'% of Cases for Screening & Cleared by Profiler – Last 30 Days Total and by Day_FR',
    'profilerResultSummary':'Red Cases and Final Verdicts – Summarised Last 30 Days_FR',
    'profilerVerdict':'Red Cases and Final Verdicts – Last 30 Days Total and by Day_FR',
    'ProfilerResultHeader':'Profiler Results Dashboard_FR',
    'imageLoadingError':'Unable to load the image. Please try again. If the problem persists, please send the Case back to your Supervisor._FR',
    'allowedImageFormats': 'Only PDF, PNG, JPEG, TIFF are allowed_FR',
    'OverAllRisk': 'Overall Risk_FR',
    'NoRulers': 'There are no rulers associated with this Case_FR',
    'Automatic':'Automatic_FR',
    'SaveInProgress' :'Save In Progress_FR',
    'PairingCase':'Pairing Case_FR',
    'Case Risk Profiler Result Updated': 'Case Risk Profiler Result Updated_FR',
    'Case Verdict Profiler Cleared':'Case Verdict Profiler Cleared_FR',
    'Sunday':'Sun_FR',
    'Monday':'Mon_FR',
    'Tuesday':'Tue_FR',
    'Wednesday':'Wed_FR',
    'Thursday':'Thu_FR',
    'Friday':'Fri_FR',
    'Saturday':'Sat_FR',
    'Jan':'Jan_FR',
    'Feb':'Feb_FR',
    'Mar':'Mar_FR',
    'Apr':'Apr_FR',
    'May':'May_FR',
    'Jun':'June_FR',
    'July':'July_FR',
    'Aug':'Aug_FR',
    'Sep':'Sep_FR',
    'Oct':'Oct_FR',
    'Nov':'Nov_FR',
    'Dec':'Dec_FR',
    'SelectBeginDate':'Select Begin Date_FR',
    'SelectEndDate':'Select End Date_FR',
    'ScanDetails':'Scan Details_FR',
    'Retry':'Retry_FR',
    'NoCasesAssigned':'There are currently no Cases assigned to you_FR',
    'scan attached':'Scan Attached_FR',
    'scan attach Failed':'Scan Attach Failed_FR'
  };
