export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
	'Login': 'Login',
	'UserId': 'User Id',
	'EnterUserId': 'Please enter user id',
	'EnterUserPassword': 'Please enter password',
	'InvalidUserPassword': 'Invalid user name or password',
	'Password': 'Password',
	'RoleName': 'Role Name',
	'Description': 'Description',
	'Status': 'Status',
	'NewRoleDescription': 'Role Description',
	'CreateNewRole': 'Create Role',
	'GeneralInformation': 'General Information',
	'RoleNameDuplicate': 'Role name already exists.',
	'RoleMandatoryFields': 'All mandatory fields must be provided to create a case',
	'RolesNotExist':'There are no roles created in the system',
	'Required': 'This is a required field',
	'OnlyNumber': 'Please enter numeric value',
	'EnterRoleName': 'Please Enter Role Name',
	'RoleExists': '%0 already exists, duplicate names not allowed please enter another name',
	'EnterRoleDescription': 'Please Enter Role Description',
	'RoleCloseMessage': 'You are leaving the window without saving it',
	'SureCloseMessage': 'Are you sure you want to leave?',
	'LeaveWithoutSaveButton': 'Leave without save',
	'BackToWindowButton': 'Back to window',
	'CasesNotExist': 'There are no Cases available in the system.',
	'TimeZone': 'Time Zone',
	'Currency': 'Currency',
	'Language': 'Language',
	'DateFormat': 'Date Format',
	'TimeFormat': 'Time Format',
	'PFRM10000': 'Role is created successfully.',
	'PFRM10001': 'Duplicate role. Role name should be unique.',
	'PFRM10002': 'Please provide all the required information for creating a role',
	'PFRM10003': 'Role Format Error. Role name should be alphanumeric with no special characters.',
	'PFRM10004': 'Role data is invalid.',
	'PFRM10100': 'Error occured while saving the role. Please try again later and contact admin if error persists.',
	'PFRM10999': 'Unknown exception occured while saving the role. Please contact admin if error persists.',
	'PFRM40100': 'Database Error occured while getting the roles. Please try again later and contact admin if error persists.',
	'PFRM30999': 'Unknown exception occured while updating the role. Please contact admin if error persists.',
	'PFRM40999': 'Unknown exception occured while getting the roles. Please contact admin if error persists.',
	'PFRM30100': 'Database error while saving the roles',
	'PFRM40000': 'Roles Details fetched successfully',
	'SACM10000': 'Case is submitted successfully.',
	'SACM10002': 'Please provide all the required information for creating a case.',
	'SACM10003': 'Case Format Error. Please make sure all the case properties are in right format.',
	'SACM10004': 'Invalid case management data.',
	'SACM10100': 'Error occured while saving the case. Please try again later and contact admin if error persists.',
	'SACM10999': 'Unknown exception occured while saving the case. Please contact admin if error persists.',
	'SACM40100': 'Database Error occured while getting the cases. Please try again later and contact admin if error persists.',
	'SACM40000': 'Case Details fetched successfully',
	'SACM40999': 'Unknown exception occured while getting the case. Please contact admin if error persists',
	'PFAM10000': 'Application was submitted successfully',
	'PFAM10002': 'Please provide all the required information for creating an Application.',
	'PFAM10003': 'Application Format Error. Please make sure all the application properties are in right format.',
	'PFAM10004': 'Invalid application data.',
	'PFAM10100': 'Error occured while saving the application. Please try again later and contact admin if error persists.',
	'PFAM10999': 'Unknown exception occured while saving the application. Please contact admin if error persists.',
	'PFAM40100': 'Database Error occured while getting the applications. Please try again later and contact admin if error persists.',
	'PFAM40000': 'Applications Details fetched successfully',
	'PFAM40999': 'Unknown exception occured while getting the apps details. Please contact admin if error persists.',
	'PFCC40100': 'Database Error occured while getting the customers data. Please try again later and contact admin if error persists.',
	'PFCC40000': 'Customers Details fetched successfully',
	'PFCC40999': 'Unknown exception occured while getting the customers details. Please contact admin if error persists.',
	'PFUM10000': 'User created successfully.',
	'PFUM10001': 'Duplicate User. User details should be unique.',
	'PFUM10002': 'Please provide all the required information for creating a user',
	'PFUM10003': 'User Format Error. User name should be alphanumeric with no special characters.',
	'PFUM10004': 'User data is invalid.',
	'PFUM10100': 'Error occured while saving the user. Please try again later and contact admin if error persists.',
	'PFUM10999': 'Unknown exception occured while saving the user. Please contact admin if error persists.',
	'PFUM40100': 'Database Error occured while getting the users. Please try again later and contact admin if error persists.',
	'PFUM40999': 'Unknown exception occured while getting the users. Please contact admin if error persists.',
	'PFUM40000': 'Users Details fetched successfully',
	'PFUM30000': 'User updated successfully.',
	'PFUM30002': 'Please provide all the required information for updating a user',
	'PFUM30003': 'User Format Error. User name should be alphanumeric with no special characters.',
	'PFUM30004': 'User data is invalid.',
	'PFUM30100': 'Error occured while saving the user. Please try again later and contact admin if error persists.',
	'PFUM30999': 'Unknown exception occured while saving the user. Please contact admin if error persists.',
	'PFUM40004': 'Error occured while getting the user details',
	'PFSM40000': 'Successful Security ',
	'PFSM40002': 'Mandatory information missing',
	'PFSM40004': 'Security data invalid',
	'ContainerID': 'Container ID',
	'Weight': 'Weight',
	'Length': 'Length',
	'From': 'From',
	'Country': 'Country',
	'OriginPort': 'Origin Port',
	'DestinationPort': 'Destination Port',
	'To': 'To',
	'Company': 'Company',
	'CreateCaseButton': 'Create Case',
	'CreateCaseSuccess': 'A new case has been submitted',
	'Alert': 'Alert',
	'Ok': 'OK',
	'Reset': 'Reset',
	'EnterContainerId': 'Please enter container ID',
	'EnterCompany': 'Please enter company',
	'ContainerLength': 'Container length should not be more than 50',
	'ContainerWeight': 'Container weight should not be more than 100',
	'NotAuthorized': 'You are not authorized to perform this action.',
	'DefaultError': 'Error occured while performing the current operation. Please try again later and contact admin if error persists.',
	'RightsReserved': 'All rights reserved',
	'Settings': 'Settings',
	'AppsNotAssigned': 'You have not been assigned any applications. Please contact admin',
	'NotAssignedApps': 'You have not assigned any Applications.',
	'Create': 'Create',
	'Cancel': 'Cancel',
	'CreateRoleQuestion': 'Do you want to create the role?',
	'Yes': 'Yes',
	'No': 'No',
	'General': 'General',
	'Users': 'Users',
	'Roles': 'Roles',
	'Applications': 'Applications',
	'Apps': 'Applications',
	'LocalSettings': 'Local Settings',
	'RegionalSettings': 'Regional Settings',
	'MeasureUnit': 'Measure Unit',
	'ChangesSave': 'Changes saved successfully',
	'NotSavedChanges': 'Warning: You have not saved your changes.',
	'LeaveMessage': 'Are you sure you want to leave?',
	'RoleInactiveMessage1': 'Warning: You have made the role inactive, there are users assigned to this role.',
	'RoleInactiveMessage2': 'The users will not be able to view this role once deactivated.',
	'RoleInactiveLeaveMessage': 'Are you sure you want to deactivate the role?',
	'RoleCreated': 'Role created',
	'FilterBy': 'Filter By',
	'Save': 'Save',
	'OrgId': 'Org ID',
	'OrgIdLabel': 'Org ID',
	'fullName': 'Full Name',
	'Id': 'ID',
	'AccountCreate': 'Account Created:',
	'Email': 'Email',
	'Telephone': 'Telephone',
	'EmpStatus': 'Employment Status',
	'Position': 'Position',
	'Mobile': 'Mobile',
	'AddNewUser': 'Add New User',
	'AddNewRole': 'Add New Role',
	'CreateUserProfile': 'Add New User',
	'NoUserFound': 'No User Found',
	'NoResultFound': 'No Result Found',
	'NotAssignedRoles': 'You have not assigned any Roles.',
	'CreateUserQuestion': 'Do you want to create the user?',
	'SaveMessageQuestion': 'Do you want to save the changes?',
	'InvalidEmail': 'Email is invalid',
	'InvalidTelephone': 'Telephone is invalid',
	'InvalidMobile': 'Mobile number is invalid',
	'GeneralSettings': 'General Settings',
	'User': 'Users',
	'MappedRoles': 'Mapped Roles',
	'AppAdded': 'App Added',
	'AppPublished': 'App Published',
	'AppLastUpdated': 'App Last Updated',
	'AppVersion': 'Version',
	'Type': 'Type',
	'Category': 'Category',
	'Arrivals': 'Arrivals',
	'MyCases': 'My Cases',
	'CreateNewCase': 'Create New Case',
	'CreateCase': 'Create a case',
	'Search': 'Search',
	'ClearAllSelected': 'Clear All Selected',
	'ScanAllSelected': 'Scan All Selected',
	'CancelAllSelected': 'Cancel All Selected',
	'CaseId': 'Case Id',
	'CaseIdText': 'Case Id:',
	'CASEID': 'FR_CASEID',
	'StartSearching': 'Start Searching',
	'UpdatedDate': 'UpdatedDate',
	'ControlCenterCaseId': 'Case Id',
	'ContainerId': 'Container Id',
	'Container': 'Container',
	'HSCode': 'Harmonised System Code',
	'HSCodes': 'Harmonised System Codes',
	'HSCodesText': 'Harmonised System Codes',
	'hscodeToolTip': 'Mutiple HSCodes should be seperated by a single comma',
	'DateCreated': 'Date Created',
	'LastModifiedDate': 'Last Modified Date',
	'LastModified': 'Last Modified',
	'ShippingCompany': 'Shipping Company',
	'DateOfArrival': 'Date of Arrival',
	'ArrivalDateSearch': 'Arrival Date',
	'ShipId': 'Ship Id',
	'ShipIdText': 'Ship Id',
	'InvalidEntry': 'Entry does not match validation criteria, please edit',
	'InvalidShipEntry': 'Entry does not match validation criteria. Ship ID Should be IMO9176187 Format).',
	'InvalidHsCodeEntry': 'Entry does not match validation criteria. HS Code Should be Numeric.',
	'InvalidWeightEntry': 'Entry does not match validation criteria. Weight should be in kgs (Up to two Decimals).',
	'InvalidContainerIDEntry': 'Entry does not match validation criteria. Container ID should be Alpha-numeric.',
	'MyDrafts': 'My Drafts',
	'AllCases': 'All Cases',
	'VehicleInformation': 'Vehicle Information',
	'PlateNumber': 'Plate Number',
	'VehicleMake': 'Vehicle Make',
	'DriverName': 'Driver Name',
	'VehicleCompany': 'Vehicle Company',
	'VehicleModal': 'Vehicle Model',
	'DriverLicense': 'Driver License',
	'ContainerInformation': 'Container Information',
	'CaseLastUpdated': 'Last Updated On',
	'CaseLastUpdatedBy': 'Last Updated By',
	'ManualCaseCreation': 'Create a case',
	'CaseDetails': 'Case Details',
	'QueryBuilder': 'Query Builder',
	'SearchCases': 'Search Cases',
	'CaseStatus': 'Status',
	'CaseStatusText': 'Status:',
	'Clear': 'Clear',
	'Scan': 'Scan',
	'cancelCase': 'Cancel This Case',
	'decideLater': 'Decide Later',
	'CargoType': 'Cargo Type:',
	'ExpandAllCasePanels': 'Expand All',
	'CollapseAllCasePanels': 'Collapse All',
	'CaseInformation': 'Case Information',
	'caseInfoActions': 'More Actions',
	'sender': 'Sender',
	'SenderAddress': 'Sender Address',
	'CaseFrom': 'Origin Country',
	'CaseTo': 'Destination Country',
	'ArrivalDate': 'Date of Arrival',
	'ArrivalDateText': 'Date of Arrival',
	'OverAllWeight': 'Overall Weight(kgs)',
	'OverAllWeightText': 'Overall Weight',
	'Notes': 'Notes',
	'NotesText': 'Notes:',
	'ShipInfomation': 'Ship Information',
	'ShipCompany': 'Shipping Company',
	'Containers': 'Container ID',
	'Contact': 'Contact',
	'Nationality': 'Nationality',
	'Attachments': 'Attachments',
	'AddAttachments': 'Add Attachments',
	'Update': 'Update',
	'SaveAsDraft': 'Save As Draft',
	'UpdateDraft': 'Update Draft',
	'CaseDraftValidationMessage': 'Case cannot be saved as draft. Please make sure to fill in the following fields: Arrival Date, Container ID and Destination Country.',
	'Delete': 'Delete',
	'Close': 'Close',
	'DeleteAllSelected': 'Delete Selected',
	'DeleteCaseQuestion': 'Are you sure you would like to delete the following case(s)?',
	'ClearAllSelectedQuestion': 'Are you sure you would like to Clear the following case(s)?',
	'CancelAllSelectedQuestion': 'Are you sure you would like to Cancel the following case(s)?',
	'ScanAllSelectedQuestion': 'Are you sure you would like to Scan the following cases?',
	'InspectAllSelectedQuestion': 'Are you sure you would like to Inspect the following case(s)?',
	'SuspectAllSelectedQuestion': 'Are you sure you would like to Suspect the following case(s)?',
	'ClearAllSelectedCasesText': 'We are going to clear following cases',
	'SuspectAllSelectedCasesText': 'We are going to suspect following cases',
	'InspectAllSelectedCasesText': 'Please select an Inspection Type for following cases',
	'ScanAllSelectedCasesText': 'We are going to scan following cases',
	'RescanAllSelectedCasesText': 'We are going to rescan the following Cases',
	'FailedCaseListText': 'The following cases have failed',
	'AwaitingScreeningSelectedCasesText': 'We are about to change the status of following cases to Awaiting Screening:',
	'SaveChanges': 'Save Changes',
	'ClearCaseQuestion': 'Are you sure you want to clear?',
	'ScanCaseQuestion': 'Are you sure you want to send to scan?',
	'SuspectCase': 'Are you sure you want to set the case as Suspect?',
	'InspectCase': 'Are you sure you want to Inspect the Case?',
	'ReScanRequest': 'Are you sure to request for Rescan of the case?',
	'CancelCaseQuestion': 'Are you sure yu want to Cancel ?',
	'UploadAttachment': 'Upload Attachment',
	'AttachmentInfo': 'Please fill the following information for this attachment',
	'Title': 'Title',
	'AttachmentDescription': ' is selected as an attachement of this case.',
	'Upload': 'Upload',
	'FieldsInfoMissing': '%0 field(s) information is missing',
	'AddNewAttachment': 'Add New Attachment',
	'Edit': 'Edit',
	'CharactersLeft': 'character(s) left',
	'ConfirmAttachmentsDelete': 'Please confirm following attachments will be deleted',
	'DeleteAttachments': 'Delete Attachments',
	'Actions': 'Actions',
	'ManageCases': 'Manage Cases',
	'Suspect': 'Suspect',
	'Activity': 'Activity',
	'Refresh': 'Refresh',
	'ViewCaseDetails': 'View Case Details',
	'Screening': 'Screening',
	'Override': 'Override',
	'Inspect': 'Inspect',
	'TrailerInformation': 'Trailer Information',
	'AssessmentImages': 'Assessment Images',
	'ImageAssessmentVerdict': 'Image Assessment Verdict',
	'InspectionEvidence': 'Inspection Evidence',
	'InspectionVerdict': 'Inspection Verdict',
	'Displaying': 'Displaying',
	'of': 'of',
	'AwaitingScreening': 'Awaiting Screening',
	'AwaitingScan': 'Awaiting Scan',
	'Awaiting Screening': 'Awaiting Screening',
	'Awaiting Scan': 'Awaiting Scan',
	'Cleared': 'Cleared',
	'Cancelled': 'Cancelled',
	'Draft': 'Draft',
	'Deleted': 'Deleted',
	'AwaitingAssessment': 'Awaiting Assessment',
	'AssessmentInProgress': 'Assessment In Progress',
	'AwaitingReAssessment': 'Re-Assessment Requested',
	'Awaiting Assessment': 'Awaiting Assessment',
	'Assessment InProgress': 'Assessment In Progress',
	'Awaiting Re-Assessment': 'Awaiting Re-Assessment',
	'Emergency': 'Emergency',
	'InspectionRequested': 'Inspection Requested',
	'AwaitingInspection': 'Awaiting Inspection',
	'InspectionInProgress': 'Inspection In Progress',
	'InspectionCleared': 'Inspection Cleared',
	'ReScanRequested': 'Rescan Requested',
	'AssessmentCleared': 'Assessment Cleared',
	'Inspection Requested': 'Inspection Requested',
	'Awaiting Inspection': 'Awaiting Inspection',
	'Inspection in Progress': 'Inspection In Progress',
	'Inspection Cleared': 'Inspection Cleared',
	'Re-Scan Requested': 'Rescan Requested',
	'Assessment Cleared': 'Assessment Cleared',
	'Priority': 'Priority',
	'Hold': 'Hold',
	'EmptyMessage': 'There are no Cases that match your query',
	'ClearCase': 'Clear Case',
	'SuspectCaseId': 'Suspect Case: ',
	'ReScanCaseId': 'The following case will be Rescanned',
	'Loading': 'Loading....',
	'ImageLoading': 'Image Loading....',
	'ApplicationLoading': 'Application Loading...',
	'RequestCaseReInspection': 'Request Inspection of Case ',
	'RequestCaseReAssess': 'Request Case Re-Assessment ',
	'EmptyReport': 'There are no finding associated to the report',
	'ImageValidaitonMessage': 'No cases to be assessed',
	'AssessmentSummary': 'Assessment Summary*',
	'LoadNextCase': 'Load Next Case',
	'MoreActions': 'MORE ACTIONS',
	'RequestReAssessment': 'Request Reassessment',
	'FitToWindow': 'Fit To Window',
	'ImageSaveMessage': 'Would you like to save these changes as a new view?',
	'NoResults': 'No Results Found',
	'NoResultsMessage': 'Try widening your search',
	'HSCodeGoodsType': 'HS Code/Goods Type',
	'LeftorRight': 'Left Or Right',
	'ToporBottom': 'Top Or Bottom',
	'FrontorBack': 'Front or Back',
	'Left': 'Left',
	'Right': 'Right',
	'Top': 'Top',
	'Bottom': 'Bottom',
	'Front': 'Front',
	'Back': 'Back',
	'ImageAnalyzer': 'Image Analyser',
	'Brightness': 'Brightness',
	'Contrast': 'Contrast',
	'DeleteFinding': 'Are you sure you want to delete the finding?',
	'DeleteFindingHeader': 'Delete Finding',
	'NoFindings': 'There are no findings associated with this Case.',
	'Finding_Category': 'Category',
	'Finding_GoodsType': 'Goods Type/ HS Code',
	'Finding_Description': 'Description',
	'RequestReAssessmentVerdict': 'Request Reassessment',
	'RequestReScanVerdict': 'Request Rescan',
	'SuspectVerdict': 'Suspect',
	'InspectVerdict': 'Inspect',
	'ClearVerdict': 'Clear',
	'ActionsVerdict': 'Actions',
	'Finding_Declare': 'Declare',
	'Finding_Declared': 'Declared',
	'Finding_Confirm': 'Confirm',
	'Finding_Confirmed': 'Confirmed',
	'RulerDeleteQuestion': 'Are you sure you want to delete the Ruler?',
	'RulerMark': 'Delete Ruler',
	'AddRuler': 'Add Ruler',
	'RulerCreationErrorMessage': 'Ruler Mark not long enough to be saved',
	'ColorPreset': 'Color Presets',
	'CaseLoading': 'Case Loading...',
	'RiskRating': 'Risk Rating',
	'LastUpdatedDate': 'Last Modified',
	'LastUpdated': 'Last Modified Date',
	'clearedCaseNote1': 'Cases available for ',
	'clearedCaseNote2': ' hours from cleared date',
	'GridClearCaseLoading': 'Loading Clear Case details',
	'PhysicalInspection': 'Physical Inspection',
	'ClearCases': 'Clear Cases',
	'Confirm': 'Confirm',
	'Comments': 'Comments',
	'PhysicalVerdict': 'Physical',
	'SelectInspectionType': '- Please select an Inspection Type',
	'SendToScreen': 'Send to Screen',
	'AwaitingInspectionCases': 'Awaiting Inspection Cases',
	'CreateNewView': 'Create New View',
	'NoOfFindings': 'No of Findings',
	'NoOfFindingsTooltip': 'No of Findings for the Case',
	'ProfilerSettings': 'Profiler Settings',
	'ReScanRequestText': 'Rescan Request',
	'BackToList': 'Back To List',
	'FindingsAndVerdict': 'Verdict',
	'DCSettings': 'Decision Center Settings',
	'ThresholdNumberRangeMessage': 'Please enter a number between 0 and 100',
	'ThresholdNumberRangeMessageDC': 'Please enter a number between 0 and 10000',
	'ThresholdTitleMessage': 'Changing the below thresholds will impact the overall Case Risk Score. All changes to these fields are recorded and audited. Please be aware that raising the threshold value results in higher risk items being passed through, and lowering the threshold value results in lower risk items being assessed.',
	'Threshold': 'Threshold',
	'RiskCategory': 'Risk Category',
	'FindingsCategory': 'Findings Category',
	'InspectionType': 'Inspection Type',
	'DiscardAndLeave': 'Discard And Leave',
	'StayInApp': 'Stay in app',
	'DiscardMessage': 'Would you like to leave the app and discard the changes?',
	'AddNewFinding': 'Add New Finding',
	'EvidenceAttached': 'Evidence Attached',
	'ConfirmNewFinding': 'The following Finding will be created, please confirm.',
	'RiskLevel': 'Risk Level',
	'RuleCategory': 'Category',
	'CategoryScore': 'Score',
	'ThresholdBreach': 'Breach',
	'CaseRiskScore': 'Case Risk Score',
	'CategoryScores': 'Category Scores',
	'CreateFinding': 'Create a new Finding',
	'CreateRuler': 'Create a new Ruler Mark',
	'CaseTimeline': 'Case Timeline',
	'batchId': 'Batch Id',
	'containerIds': 'Container Id',
	'scanTime': 'Scan Time',
	'NoFilteredCases': 'There are no Cases available for inspection.',
	'NoFilteredInspectionCases': 'There are no Cases of ' + 'xxxx' + ' Inspection Type. Please clear filter or select another Inspection type.',
	'NoFilteredFindingCases': 'There are no Cases of ' + 'xxxx' + ' Findings Category. Please clear filter or select another Findings Category.',
	'RAPPathway': 'RAP Pathway',
	'RapColour': 'RAP Colour',
	'RapColourStatus': 'Initial Case status',
	'MinRapScore': 'Minimum RAP Score',
	'MaxRapScore': 'Maximum RAP Score',
	'rapValidMessage': 'Please enter valid range number',
	'ScanId': 'Scan Id',
	'ScanDateTime': 'Date & Time Scan Created',
	'SelectScanner': 'Select Scanner',
	'FilterTable': 'Filter Table',
	'ApplyFilter': 'Apply Filter',
	'LoadScanner': 'Load Scanner',
	'ChangeScanner': 'Change Scanner',
	'ScanDate': 'Scan Date',
	'AssociationStatus': 'Association Status',
	'RiskScore': 'Risk Score',
	'DCSetting': 'DC Settings',
	'RapErrorMessage': 'Invalid value entered in Min/Max RAP Score field',
	'English': 'English',
	'French': 'French',
	'German': 'German',
	'AwaitingProfiling': 'Awaiting Profiling',
	'CurrentStatus': 'Current Status',
	'Ship': 'Shipping Information',
	'DeparturePort': 'Departure Port',
	'DepartureDate': 'Departure Date',
	'MatchCaseHeaderText': 'Display Matching Case',
	'MatchCaseInfoText': 'The following case matches the case information submitted. Can you either confirm that these are the same cases or that they are different cases',
	'ShippingNationality': 'Nationality',
	'ShippingContact': 'Contact',
	'SerialNumber': 'Serial Number',
	'Manufacturer': 'Manufacturer',
	'DeviceID': 'Device Id',
	'Display': 'Display',
	'LocationSetting': 'Locations',
	'UserName': 'User Name',
	'ModelName': 'Model Name',
	'Latitude': 'Location.Latitude',
	'Longitude': 'Location.Longitude',
	'Location': 'Location',
	'AssignedLicense': 'License',
	'NoLicense': 'No Device License Available',
	'NoUserLicense': 'No User License Available',
	'DeviceSetting': 'Device Settings',
	'AssessmentSummaryText': 'Assessment Summary',
	'VerdictStatus': 'Verdict Status',
	'operationalDashboard': 'Operational Dashboard',
	'AssignLicense': 'License',
	'Active': 'Active',
	'Inactive': 'Inactive',
	'None': 'None',
	'Disabled': 'Disabled',
	'ToggleLicenseFailure': 'Failure to Apply License',
	'TargetImageAccessed': 'Target Images Assessed (per User per Hour)',
	'FindingNumber': 'Finding Number',
	'caseDetailId': 'Id',
	'FindingAttachments': 'Finding Attachments',
	'FileName': 'File Name',
	'FileData': 'File Data',
	'FileDescription': 'File Description',
	'SelectedLocation': 'Location',
	//dashboard translate constant
	'KPIS': 'KPIS',
	'ScreenedAssessed': 'Screened & Assessed',
	'Screened': 'Screened',
	'Inspected': 'Inspected',
	'Suspected': 'Suspected',
	'TotalAssessments': 'Total Assessments',
	'Target': 'TARGET',
	'Actual': 'ACTUAL',
	'Name': 'Name',
	'ShowHide': 'Show/Hide',
	'Green': 'Green',
	'Amber': 'Amber',
	'Red': 'Red',
	'Blue': 'Blue',
	'ImageAssesmentTitle': 'Image Assessment Compared to Target',
	'Today': 'Today',
	'Last24': 'Last 24 HRS',
	'ActualLegend': 'Actual',
	'TargetLegend': 'Target',
	'ProfilerchartHeader': 'Profiler Resource Forecast Chart',
	'TotalChart': 'Total Chart',
	'TotalExpected': 'Total Expected',
	'TotalProfiled': 'Total Profiled',
	'RapColorChart': 'RAP Colour Chart',
	'ProfiledCases': 'Profiled Cases',
	'ExpectedCase': 'Expected Case',
	'TotalProfiledCases': 'Total Profiled Cases',
	'TotalExpectedCases': 'Total Expected Cases',
	'SecureRedirection': 'Redirecting to Secure Login Page...',
	'UnauthorisedAccess': 'Unauthorised Access',
	'AdminContactMessage': 'You are not a registered user or your account does not have a valid licence. Please contact the system administrator',
	'Attached': 'Attached',
	'UserTimeline': 'User',
	'NoRecordsFound': 'No records found',
	'NoAttachmentsFound': 'No attachments found',
	'ScanToColourMapping': 'Convert Scan to Colour Mapping',
	'ScanToOriginalGreyscale': 'Convert Scan to original Greyscale',
	'Organic': 'Organic',
	'NonOrganic': 'Non-Organic',
	'Metal': 'Metal',
	'ShowFindings': 'Show Findings for this scan',
	'HideFindings': 'Hide Findings for this scan',
	'ShowRulers': 'Show Rulers for this scan',
	'HideRulers': 'Hide Rulers for this scan',
	'Effects': 'Effects',
	'Vizual': 'ViZual',
	'FitToView': 'Fit view',
	'UserLoading': 'Loading Users...',
	'UserDetailLoading': 'Loading User Details',
	'SettingsLoading': 'Loading Settings...',
	'SaveSettingsLoading': 'Save Settings',
	'GeneralSettingsHeader': 'General Settings',
	'UsersUpdating': 'Updating User...',
	'UsersSaving': 'Saving User...',
	'RolesUpdating': 'Updating Role...',
	'RolesSaving': 'Saving Role...',
	'RoleDetailLoading': 'Loading Role Details...',
	'RoleLoading': 'Loading Roles...',
	'SessionTimeout': 'Session has expired',
	'SessionExpireMessage': 'You have been logged out due to inactivity.',
	'SessionRoute': 'Click here to login',
	'Note': 'Note',
	'ApplDetailLoading': 'Loading Application Details...',
	'AppInformation': 'Applications Information',
	'AppsUpdating': 'Updating Application...',
	'ProfilerInfo': 'Profiler Information',
	'ProfilerSettingsLoading': 'Loading Profiler Settings...',
	'ProfilerSettingsSaving': 'Saving Profiler Settings...',
	'RAPPathwayInfo': 'RAP Pathway Information',
	'RAPPathwayLoading': 'Loading RAP Pathway Settings...',
	'RAPPathwaySaving': 'Saving RAP Pathway Settings...',
	'Parameter': 'Parameter',
	'Value': 'Value',
	'DeviceLicenseInfo': 'Device License Information',
	'DeviceDetailLoading': 'Loading Device Details...',
	'DeviceDetailSaving': 'Saving Device Details...',
	'DecisionCentre': 'Decision Centre',
	'DecisionCenterInfo': 'Decision Centre Settings',
	'DecisionCenterLoading': 'Loading Decision Centre Settings...',
	'DecisionCenterSaving': 'Saving Decision Centre Settings...',
	'LocationsInformation': 'Locations Information',
	'LocationLoading': 'Loading Locations...',
	'LocationID': 'Location Id',
	'LocationName': 'Location Name',
	'LocationCode': 'Location Code',
	'OperationalDashBoardSetting': 'Operational Dashboard Settings',
	'Detail': 'Detail',
	'Timeline': 'Timeline',
	'SavedViews': 'Saved Views',
	'Verdict': 'Verdict',
	'LogOut': 'Log out',
	'CategoryType': 'Category Type',
	'NIIStatus': 'For NII -Status',
	'RAPSelectedStatus': 'For (RAD/NUC, De-Stuff, Canine) - Status',
	'Source': 'Source',
	'ImageAssessment': 'Image Assessment',
	'Findings': 'Findings',
	'Finding': 'Finding',
	'Action': 'Action',
	'ApprovalRequest': 'Approval Request',
	'ApprovalRequestType': 'Approval Request Type',
	'HsCodeOrGoodsType': 'HSCode / Goods Type',
	'CaseCreation': 'Case Creation',
	'Profiler': 'Profiler',
	'View': 'View',
	'Ruler': 'Ruler',
	'InspectorAssigned': 'Inspector Assigned',
	'InspectorVerdict': 'Inspector Verdict',
	'CasePriority': 'Case Priority',
	'CaseHold': 'Case Hold',
	'RiskColor': 'Risk Color',
	'Date': 'Date',
	'Manual': 'Manual',
	'Attachment': 'Attachment',
	'UserLabel': 'User',
	'Evidence': 'Evidence',
	'AssignToSelf': 'Assign To Self',
	'Approval': 'Approval',
	'EnterContainerIDLabel': 'Enter Container ID',
	'EnterContainerIDNumber': 'Enter Container ID Number',
	'CorsysScanId': 'CORSYS Scan Id',
	'FindCase': 'Find Case',
	'PairCase': 'Pair Case',
	'Pair': 'Pair',
	'NoCaseFound': 'No case found with this Container ID',
	'CheckCase': 'Please double check the number is correct or create a new case.',
	'ZoomIn': 'zoom+',
	'ZoomOut': 'zoom-',
	'DisplayOn': 'Display On',
	'DisplayOff': 'Display Off',
	'AddMark': 'Add Mark',
	'SaveComment': 'Save Comment',
	'SelectFromList': 'Select from list',
	'CancelCase': 'Cancel the Case',
	'Submit': 'Submit',
	'Leave': 'Leave',
	'Assessment': 'Assessment',
	'RulerId': 'Ruler Id',
	'Shapes': 'Shapes',
	'AssessmentDetails': 'Assessment Details',
	'Comment': 'Comments',
	'ScanAssociationFailed': 'The Scan has failed to associate with the case, please try again',
	'Success': 'Success',
	'StatusUpdated': 'Status Updated',
	'InspectCaseText': 'Inspect Case',
	'SuspectCaseText': 'Suspect Case',
	'VerdictClearCase': 'Verdict - Clear Case',
	'VerdictInspectCase': 'Verdict - Inspect Case',
	'VerdictSuspectCase': 'Verdict - Suspect Case',
	'UploadEvidence': 'Upload Evidence',
	'VerdictCase': 'Verdict: Case:',
	'SaveFinding': 'Save Finding',
	'LocationTitle': 'Select a location',
	'Heroin': 'Heroin',
	'Destuff': 'De-stuff',
	'Canine': 'Canine',
	'RADNUC': 'RAD/NUC',
	'Cocaine': 'Cocaine',
	'Marijuana': 'Marijuana',
	'Guns': 'Guns',
	'weapons': 'Weapons',
	'drugs': 'Drugs',
	'Knives': 'Knives',
	'undeclared': 'Undeclared',
	'SupervisorCaseCleared': 'Supervisor - Case Cleared',
	'RapSelected': 'Rap Selected',
	'ScanAssociated': 'Scan – Scan Associated',
	'AnalyserReAssessment': 'Analyser - Re-assessment',
	'AnalyserfindingCreated': 'Analyser Findings - Created',
	'AnalyserfindingUpdated': 'Analyser Findings - Updated',
	'AnalyserfindingDeleted': 'Analyser Findings - Deleted',
	'AnalyserRulersDeleted': 'Analyser Rulers - Deleted',
	'AnalyserRulersUpdated': 'Analyser Rulers - Updated',
	'AnalyserRulersCreated': 'Analyser Rulers - Created',
	'AnalyserViewsCreated': 'Analyser Views - Created',
	'AnalyserViewsUpdated': 'Analyser Views - Updated',
	'AnalyserVerdictCleared': 'Analyser Verdict - Cleared',
	'AnalyserVerdictSuspect': 'Analyser Verdict - Suspect',
	'AnalyserVerdictInspect': 'Analyser Verdict - Inspect',
	'SupervisorRescanRequestApproval': 'Supervisor - Rescan Re-Request Approval',
	'SupervisorFlagHoldOnHold': 'Supervisor - Flag – Hold – On Hold',
	'SupervisorFlagHoldRemoved': 'Supervisor - Flag – Hold – Removed',
	'SupervisorFlagPriorityCase': 'Supervisor - Flag – Priority – Case Prioritized',
	'SupervisorFlagPriorityRemoved': 'Supervisor - Flag – Priority – Removed',
	'InspectionInspectorAssignedCase': 'Inspection - Inspector Assigned',
	'InspectionVerdictCleared': 'Inspection - Verdict – Cleared',
	'InspectionVerdictSuspect': 'Inspection - Verdict – Suspect',
	'InspectionVerdictAddNewFinding': 'Inspection - Verdict – Add New Finding',
	'InspectionVerdictEvidence': 'Inspection - Verdict – Evidence',
	'InspectionFindingsDeleted': 'Inspection – Findings – Deleted',
	'InspectionFindingsUpdated': 'Inspection – Findings – Updated',
	'InspectionFindingsCreated': 'Inspection – Findings – Created',
	'InspectionRulersUpdated': 'Inspection – Rulers – Updated',
	'InspectionRulersDeleted': 'Inspection – Rulers – Deleted',
	'ManualCaseCreatedFileAttachment': 'Manual Case Created – File Attachment',
	'ProfilerResult': 'Profiler Result',
	'ProfilerResultHeader': 'Profiler Results Dashboard',
	'ManualCaseCreated': 'Manual Case Created',
	'SupervisorDeStuffInspect': 'Supervisor -De-Stuff- Inspect',
	'SupervisorRADInspect': 'Supervisor -RAD/NUC- Inspect',
	'SupervisorCanineInspect': 'Supervisor -Canine- Inspect',
	'SupervisorNIIScan': 'Supervisor - NII - Scan',
	'AnalyserInspect': 'Analyser - Inspect',
	'AnalyserReScan': 'Analyser Rescan',
	'InspectionRulersCreated': 'Inspection – Rulers – Created',
	'SupervisorInspectionApproved': 'Supervisor - Inspection Approved – Inspect',
	'SupervisorDecisionOverride': 'Supervisor - Decision Override',
	'Inspection': 'Inspection',
	'InspectionVerdictInspect': 'Inspection - Verdict – Inspect',
	'InspectionDuration': 'Inspection Duration',
	'AllRoles': 'All Roles',
	'ActiveRoles': 'Active Roles',
	'InactiveRoles': 'Inactive Roles',
	'AllUsers': 'All Users',
	'ActiveUsers': 'Active Users',
	'InactiveUsers': 'Inactive Users',
	'AllApps': 'All Apps',
	'ActiveApps': 'Active Apps',
	'InactiveApps': 'Inactive Apps',
	'ReScan': 'Rescan',
	'Choose': 'Choose',
	'DecisionVerdictSuspect': 'Decision - Verdict – Suspect',
	'Confirmed': 'Confirmed',
	'Declared': 'Declared',
	'Dashboard': 'Dashboard',
	'ProfilerDashboard': 'Profiler Dashboard',
	'OperationalDashboard': 'Operational Dashboard',
	'DurationMins': 'Duration (Mins)',
	'DurationHrs': 'Duration (Hrs)',
	'HideRuler': 'Hide',
	'DeleteRuler': 'Delete',
	'DuplicateAction': 'Duplicate Performed',
	'profilerResultDashboard': '% of Cases for Screening & Cleared by Profiler – Last 30 Days Total and by Day',
	'profilerVerdict': 'Red Cases and Final Verdicts – Last 30 Days Total and by Day',
	'profilerResultSummary': 'Red Cases and Final Verdicts – Summarised Last 30 Days',
	'imageLoadingError': 'Unable to load the image. Please try again. If the problem persists, please send the Case back to your Supervisor.',
	'allowedImageFormats': 'Only PDF, PNG, JPEG, TIFF are allowed',
	'OverAllRisk': 'Overall Risk',
	'NoRulers': 'There are no rulers associated with this Case.',
	'Automatic': 'Automatic',
	'SaveInProgress': 'Save In Progress',
	'PairingCase': 'Pairing Case',
	'Case Risk Profiler Result Updated': 'Case Risk Profiler Result Updated',
	'Case Verdict Profiler Cleared': 'Case Verdict Profiler Cleared',
	'Sunday': 'Sun',
	'Monday': 'Mon',
	'Tuesday': 'Tue',
	'Wednesday': 'Wed',
	'Thursday': 'Thu',
	'Friday': 'Fri',
	'Saturday': 'Sat',
	'Jan': 'Jan',
	'Feb': 'Feb',
	'Mar': 'Mar',
	'Apr': 'Apr',
	'May': 'May',
	'Jun': 'June',
	'July': 'July',
	'Aug': 'Aug',
	'Sep': 'Sep',
	'Oct': 'Oct',
	'Nov': 'Nov',
	'Dec': 'Dec',
	'SelectBeginDate': 'Select Begin Date',
	'SelectEndDate': 'Select End Date',
	'ScanDetails': 'Scan Details',
	'Retry': 'Retry',
	'NoCasesAssigned':'There are currently no Cases assigned to you',
	'scan attached':'Scan Attached',
	'scan attach Failed':'Scan Attach Failed'
};
